/-
ToeFormal/QFT/ContinuumBaseSpaceIntegralModel.lean

Bounded base-space/integral model surface for PHASE1-BLOCKER-003A1A1.

Scope:
- define the minimal base-domain and integral/pairing model needed by the
  selected scalar kinetic operator/function-space pair
- construct the selected scalar kinetic pair from that model
- show how the model feeds `ConcreteCalculusSemantics` when the remaining
  differentiability, decay, trace, and variation-closure interpretations are
  supplied
- record the exact retained base/integral objects that still block an
  unconditional concrete calculus semantics source
- keep Green identity, closed boundary universe, integration regularity,
  operator-domain closure, residual separation, and Phase 2 authorization out
  of scope
-/

import ToeFormal.QFT.ContinuumConcreteCalculusSemantics

namespace ToeFormal
namespace QFT
namespace ContinuumBaseSpaceIntegralModel

open ContinuumFirstVariation
open ContinuumAnalyticBlocker003
open ContinuumBoundaryTermModel
open ContinuumGreenIdentityRetained
open ContinuumGreenIdentityAttempt
open ContinuumDifferentiableFunctionSpace
open ContinuumConcreteCalculusSemantics
set_option autoImplicit false

noncomputable section

/-- Exact retained id for the base-space/integral-model slice. -/
def phase1Blocker003A1A1BaseSpaceIntegralModelId : String :=
  "PHASE1-BLOCKER-003A1A1_BASE_SPACE_INTEGRAL_MODEL_RETAINED"

/-- The base domain used by the continuum scalar field model. -/
abbrev BaseDomain (Point : Type) := Point

/-- The scalar codomain used by the current continuum scalar route. -/
abbrev ScalarFieldCodomain := Real

/-- Concrete objects still needed to instantiate the base-space/integral model. -/
inductive Phase1Blocker003A1A1BaseIntegralMissingObject where
  | concreteBaseDomain
  | integralFunctionalConstruction
  | pairingCompatibility
  | integralLinearityAssumption
  | scalarKineticOperatorCompatibility
  | boundaryTraceCompatibility
deriving DecidableEq, Repr

/-- Machine-facing ids for the retained base-space/integral objects. -/
def phase1Blocker003A1A1BaseIntegralMissingObjectId :
    Phase1Blocker003A1A1BaseIntegralMissingObject → String
  | .concreteBaseDomain =>
      "003A1A1_CONCRETE_BASE_DOMAIN_RETAINED"
  | .integralFunctionalConstruction =>
      "003A1A1_INTEGRAL_FUNCTIONAL_CONSTRUCTION_RETAINED"
  | .pairingCompatibility =>
      "003A1A1_PAIRING_COMPATIBILITY_RETAINED"
  | .integralLinearityAssumption =>
      "003A1A1_INTEGRAL_LINEARITY_ASSUMPTION_RETAINED"
  | .scalarKineticOperatorCompatibility =>
      "003A1A1_SCALAR_KINETIC_OPERATOR_COMPATIBILITY_RETAINED"
  | .boundaryTraceCompatibility =>
      "003A1A1_BOUNDARY_TRACE_COMPATIBILITY_RETAINED"

/-- Exact retained base-space/integral objects after this bounded slice. -/
def phase1Blocker003A1A1BaseIntegralMissingObjectsV0 :
    List Phase1Blocker003A1A1BaseIntegralMissingObject :=
  [ .concreteBaseDomain
  , .integralFunctionalConstruction
  , .pairingCompatibility
  , .integralLinearityAssumption
  , .scalarKineticOperatorCompatibility
  , .boundaryTraceCompatibility
  ]

/-- The current retained base-space/integral object list is explicit. -/
theorem phase1_blocker003a1a1_base_integral_missing_objects_v0_expected :
    phase1Blocker003A1A1BaseIntegralMissingObjectsV0 =
      [ .concreteBaseDomain
      , .integralFunctionalConstruction
      , .pairingCompatibility
      , .integralLinearityAssumption
      , .scalarKineticOperatorCompatibility
      , .boundaryTraceCompatibility
      ] := by
  rfl

/--
Minimal base-space/integral model for the selected scalar kinetic pair.

The `Point` parameter is the base domain.  The scalar codomain is fixed to
`Real` by `ContinuumField`.  Linearity and compatibility are recorded as
explicit supplied source assumptions; they are not derived here from measure or
manifold analysis.
-/
structure BaseSpaceIntegralModel (Point : Type) where
  base_domain_source : Prop
  base_domain_source_supplied : base_domain_source
  integral_model_source : Prop
  integral_model_source_supplied : integral_model_source
  integral : ContinuumField Point → Real
  pairing : ContinuumField Point → ContinuumField Point → Real
  pairing_eq_continuum_pair :
    ∀ x y : ContinuumField Point,
      pairing x y = ContinuumPair integral x y
  integral_linearity_assumption : Prop
  integral_linearity_assumption_supplied :
    integral_linearity_assumption
  kineticOperator : ContinuumField Point → ContinuumField Point
  trace : TwoSidedBoundaryTrace Point
  FieldSmooth : ContinuumField Point → Prop
  InOperatorDomain : ContinuumField Point → Prop
  scalar_kinetic_pair_compatible : Prop
  scalar_kinetic_pair_compatible_supplied :
    scalar_kinetic_pair_compatible

/-- The selected scalar kinetic pair generated by a base-space/integral model. -/
def scalarKineticPairOfBaseSpaceIntegralModel {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    ScalarKineticOperatorFunctionSpacePair Point where
  integral := model.integral
  kineticOperator := model.kineticOperator
  trace := model.trace
  FieldSmooth := model.FieldSmooth
  InOperatorDomain := model.InOperatorDomain

/-- The generated pair preserves the model integral. -/
theorem base_space_integral_model_pair_integral_eq {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    (scalarKineticPairOfBaseSpaceIntegralModel model).integral =
      model.integral := by
  rfl

/-- The generated pair preserves the model kinetic operator. -/
theorem base_space_integral_model_pair_operator_eq {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    (scalarKineticPairOfBaseSpaceIntegralModel model).kineticOperator =
      model.kineticOperator := by
  rfl

/-- The model pairing is the continuum pairing induced by the generated pair. -/
theorem base_space_integral_model_pairing_eq_continuum_pair {Point : Type}
    (model : BaseSpaceIntegralModel Point)
    (x y : ContinuumField Point) :
    model.pairing x y =
      ContinuumPair (scalarKineticPairOfBaseSpaceIntegralModel model).integral
        x y := by
  exact model.pairing_eq_continuum_pair x y

/-- The generated pair targets the selected scalar kinetic boundary problem. -/
theorem base_space_integral_model_pair_selected {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    ScalarKineticBoundaryProblemSelected
      (scalarKineticBoundaryProblemOfPair
        (scalarKineticPairOfBaseSpaceIntegralModel model)) := by
  exact scalar_kinetic_boundary_problem_of_pair_selected
    (scalarKineticPairOfBaseSpaceIntegralModel model)

/--
Remaining semantics interpretations over a supplied base-space/integral model.

This separates the base/integral data from the still-retained calculus
interpretations needed to construct `ConcreteCalculusSemantics`.
-/
structure BaseSpaceIntegralSemanticsInterpretation {Point : Type}
    (model : BaseSpaceIntegralModel Point) where
  FieldSpace : ContinuumField Point → Prop
  TestVariationSpace : ContinuumField Point → Prop
  DifferentiableRegular : ContinuumField Point → Prop
  CompactSupportOrBoundaryDecay : ContinuumField Point → Prop
  TraceExists : ContinuumField Point → Prop
  interpretation_source : Prop
  interpretation_source_supplied : interpretation_source
  field_regular :
    ∀ f : ContinuumField Point,
      FieldSpace f → DifferentiableRegular f
  variation_regular :
    ∀ eta : ContinuumField Point,
      TestVariationSpace eta → DifferentiableRegular eta
  field_smooth :
    ∀ f : ContinuumField Point,
      FieldSpace f → model.FieldSmooth f
  variation_smooth :
    ∀ eta : ContinuumField Point,
      TestVariationSpace eta → model.FieldSmooth eta
  field_decay :
    ∀ f : ContinuumField Point,
      FieldSpace f → CompactSupportOrBoundaryDecay f
  variation_decay :
    ∀ eta : ContinuumField Point,
      TestVariationSpace eta → CompactSupportOrBoundaryDecay eta
  field_trace_exists :
    ∀ f : ContinuumField Point,
      FieldSpace f → TraceExists f
  variation_trace_exists :
    ∀ eta : ContinuumField Point,
      TestVariationSpace eta → TraceExists eta
  trace_vanishing_of_decay :
    ∀ f : ContinuumField Point,
      CompactSupportOrBoundaryDecay f →
        TraceVanishingCompactSupportOrDecay
          (scalarKineticBoundaryProblemOfPair
            (scalarKineticPairOfBaseSpaceIntegralModel model)) f
  variation_family_closed :
    ∀ (phi eta : ContinuumField Point) (eps : Real),
      FieldSpace phi →
      TestVariationSpace eta →
        FieldSpace (VariationFamily phi eta eps)
  test_variations_add_closed :
    ∀ eta zeta : ContinuumField Point,
      TestVariationSpace eta →
      TestVariationSpace zeta →
        TestVariationSpace (fieldAdd eta zeta)
  test_variations_smul_closed :
    ∀ (a : Real) (eta : ContinuumField Point),
      TestVariationSpace eta →
        TestVariationSpace (fieldSMul a eta)

/--
Construct concrete calculus semantics from a base-space/integral model plus
the remaining calculus interpretations.
-/
def concreteCalculusSemanticsOfBaseSpaceIntegralModel {Point : Type}
    (model : BaseSpaceIntegralModel Point)
    (interp : BaseSpaceIntegralSemanticsInterpretation model) :
    ConcreteCalculusSemantics
      (scalarKineticPairOfBaseSpaceIntegralModel model) where
  FieldSpace := interp.FieldSpace
  TestVariationSpace := interp.TestVariationSpace
  DifferentiableRegular := interp.DifferentiableRegular
  CompactSupportOrBoundaryDecay := interp.CompactSupportOrBoundaryDecay
  TraceExists := interp.TraceExists
  calculus_semantics_source :=
    model.base_domain_source ∧
      model.integral_model_source ∧
      model.integral_linearity_assumption ∧
      model.scalar_kinetic_pair_compatible ∧
      interp.interpretation_source
  calculus_semantics_source_supplied := by
    exact ⟨model.base_domain_source_supplied,
      model.integral_model_source_supplied,
      model.integral_linearity_assumption_supplied,
      model.scalar_kinetic_pair_compatible_supplied,
      interp.interpretation_source_supplied⟩
  field_regular := interp.field_regular
  variation_regular := interp.variation_regular
  field_smooth := interp.field_smooth
  variation_smooth := interp.variation_smooth
  field_decay := interp.field_decay
  variation_decay := interp.variation_decay
  field_trace_exists := interp.field_trace_exists
  variation_trace_exists := interp.variation_trace_exists
  trace_vanishing_of_decay := interp.trace_vanishing_of_decay
  variation_family_closed := interp.variation_family_closed
  test_variations_add_closed := interp.test_variations_add_closed
  test_variations_smul_closed := interp.test_variations_smul_closed

/-- A base-space/integral model plus interpretations supplies the 003A1 model. -/
theorem base_space_integral_model_feeds_differentiable_model
    {Point : Type}
    (model : BaseSpaceIntegralModel Point)
    (interp : BaseSpaceIntegralSemanticsInterpretation model) :
    ScalarKineticDifferentiableFunctionSpaceModel
      (scalarKineticPairOfBaseSpaceIntegralModel model) := by
  exact concrete_calculus_semantics_supplies_function_space_model
    (scalarKineticPairOfBaseSpaceIntegralModel model)
    (concreteCalculusSemanticsOfBaseSpaceIntegralModel model interp)

/-- The model's base-domain source is explicit. -/
theorem base_space_integral_model_base_domain_source_supplied
    {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    model.base_domain_source :=
  model.base_domain_source_supplied

/-- The model's integral source is explicit. -/
theorem base_space_integral_model_integral_source_supplied
    {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    model.integral_model_source :=
  model.integral_model_source_supplied

/-- The model's pair-compatibility source is explicit. -/
theorem base_space_integral_model_pair_compatibility_supplied
    {Point : Type}
    (model : BaseSpaceIntegralModel Point) :
    model.scalar_kinetic_pair_compatible :=
  model.scalar_kinetic_pair_compatible_supplied

/--
003A1A1 readout.  The base-space/integral surface can build the selected pair
and feed concrete semantics conditionally, but no actual base/integral source
is constructed here.
-/
def phase1Blocker003A1A1BaseSpaceIntegralModelV0 :
    Phase1Blocker003Split where
  boundaryTermVanishingStatus := .dischargedConditional
  operatorDomainClosureStatus := .retained
  residualSeparationStatus := .retained
  smoothnessAdmissibleVariationStatus := .retained
  integrationLinearityStatus := .retained
  phase2Authorized := False

/-- Phase 2 remains unauthorized after the base-space/integral-model slice. -/
theorem phase1_blocker003a1a1_base_integral_v0_phase2_not_authorized :
    ¬ phase1Blocker003A1A1BaseSpaceIntegralModelV0.phase2Authorized := by
  intro h
  exact h

end
end ContinuumBaseSpaceIntegralModel
end QFT
end ToeFormal
