/-
ToeFormal/QFT/ScalarPotentialDecomposition.lean

Explicit scalar-potential decomposition surface for the bounded free-scalar
route.

Scope:
- make the quadratic coefficient convention explicit
- expose a separate nonlinear remainder object
- build the document-level free-scalar decomposition from that split
- prove that the quadratic free-scalar regime reduces the potential
  contribution to the mass term used by the scalar witness
- no claim of unique document parsing, global master-action promotion,
  interacting-QFT completion, seam closure, or empirical validation

This file narrows a previous retained assumption: the scalar potential split is
now a named object with a named quadratic-regime theorem, while the
document-to-split assignment remains explicit and assumption-bearing.
-/

import ToeFormal.QFT.DocumentMasterActionMapping

namespace ToeFormal
namespace QFT
namespace ScalarPotentialDecomposition

open ContinuumFirstVariation
open DocumentMasterActionMapping
set_option autoImplicit false

noncomputable section

/-- Explicit split of the scalar potential into quadratic and nonlinear parts. -/
structure PotentialSplit where
  effectiveQuadraticCoeff : Real
  nonlinearRemainder : Real

/--
Explicit assignment from document-level scalar-potential tokens to a chosen
potential split.

This does not parse the document. It records which document tokens are being
read as the quadratic and nonlinear parts, together with the split they are
assigned to.
-/
structure DocumentPotentialAssignment where
  quadraticToken : DocumentTermToken
  remainderToken : DocumentTermToken
  split : PotentialSplit

/--
Machine-checkable certificate describing how a source artifact selects the
scalar-potential tokens, their classes, and the resulting split.

This is a bounded fidelity object, not a parser. It records a checkable bridge
from a named source surface to a `DocumentPotentialAssignment`.
-/
structure ScalarPotentialAssignmentCertificate where
  sourceSpecId : String
  quadraticToken : DocumentTermToken
  quadraticClass : DocumentTermClass
  remainderToken : DocumentTermToken
  remainderClass : DocumentTermClass
  split : PotentialSplit

/--
Structured source for scalar-potential assignment inputs.

This is a machine-facing object intended to be authored directly (or generated
from a richer upstream source) so certificate generation is no longer a bare
curated literal in the witness layer.
-/
structure StructuredScalarPotentialSource where
  sourceSpecId : String
  quadraticToken : DocumentTermToken
  remainderToken : DocumentTermToken
  effectiveQuadraticCoeff : Real
  nonlinearRemainder : Real

/-- Structured source split projection. -/
def structuredSourcePotentialSplit
    (source : StructuredScalarPotentialSource) : PotentialSplit where
  effectiveQuadraticCoeff := source.effectiveQuadraticCoeff
  nonlinearRemainder := source.nonlinearRemainder

/-- Structured source to certificate generation. -/
def certificateFromStructuredSource
    (source : StructuredScalarPotentialSource) : ScalarPotentialAssignmentCertificate where
  sourceSpecId := source.sourceSpecId
  quadraticToken := source.quadraticToken
  quadraticClass := classifyDocumentTerm source.quadraticToken
  remainderToken := source.remainderToken
  remainderClass := classifyDocumentTerm source.remainderToken
  split := structuredSourcePotentialSplit source

/--
Validity condition for structured scalar-potential sources in the bounded
free-scalar route.
-/
def StructuredScalarPotentialSourceValid
    (source : StructuredScalarPotentialSource) : Prop :=
  source.quadraticToken = DocumentTermToken.scalarPotentialQuadratic ∧
    source.remainderToken = DocumentTermToken.scalarInteractionRemainder

/--
The selected document tokens must land in the scalar-mass and interaction
classes expected by the potential split.
-/
def DocumentPotentialAssignmentValid
    (assignment : DocumentPotentialAssignment) : Prop :=
  classifyDocumentTerm assignment.quadraticToken = DocumentTermClass.scalarMass ∧
    classifyDocumentTerm assignment.remainderToken = DocumentTermClass.interaction

/-- Assignment generated by a scalar-potential certificate. -/
def certificateGeneratedAssignment
    (certificate : ScalarPotentialAssignmentCertificate) :
    DocumentPotentialAssignment where
  quadraticToken := certificate.quadraticToken
  remainderToken := certificate.remainderToken
  split := certificate.split

/--
Validity of a certificate: the recorded classes must be the expected ones and
must agree with the document token classifier.
-/
def ScalarPotentialAssignmentCertificateValid
    (certificate : ScalarPotentialAssignmentCertificate) : Prop :=
  certificate.quadraticClass = DocumentTermClass.scalarMass ∧
    certificate.remainderClass = DocumentTermClass.interaction ∧
    classifyDocumentTerm certificate.quadraticToken = certificate.quadraticClass ∧
    classifyDocumentTerm certificate.remainderToken = certificate.remainderClass

/-- The generated assignment uses exactly the fields recorded in the certificate. -/
theorem certificate_generated_assignment_uses_certificate_fields
    (certificate : ScalarPotentialAssignmentCertificate) :
    (certificateGeneratedAssignment certificate).quadraticToken =
        certificate.quadraticToken ∧
      (certificateGeneratedAssignment certificate).remainderToken =
        certificate.remainderToken ∧
      (certificateGeneratedAssignment certificate).split = certificate.split := by
  exact ⟨rfl, rfl, rfl⟩

/-- Structured-source-generated certificates always match classifier-consistent classes. -/
theorem certificate_from_structured_source_valid
    (source : StructuredScalarPotentialSource)
    (hSource : StructuredScalarPotentialSourceValid source) :
    ScalarPotentialAssignmentCertificateValid
      (certificateFromStructuredSource source) := by
  rcases hSource with ⟨hQuadraticToken, hRemainderToken⟩
  have hQuadraticClass :
      classifyDocumentTerm source.quadraticToken = DocumentTermClass.scalarMass := by
    calc
      classifyDocumentTerm source.quadraticToken =
          classifyDocumentTerm DocumentTermToken.scalarPotentialQuadratic := by
            simpa [hQuadraticToken]
      _ = DocumentTermClass.scalarMass := rfl
  have hRemainderClass :
      classifyDocumentTerm source.remainderToken = DocumentTermClass.interaction := by
    calc
      classifyDocumentTerm source.remainderToken =
          classifyDocumentTerm DocumentTermToken.scalarInteractionRemainder := by
            simpa [hRemainderToken]
      _ = DocumentTermClass.interaction := rfl
  refine ⟨hQuadraticClass, hRemainderClass, ?_, ?_⟩
  · rfl
  · rfl

/-- Valid structured sources generate valid document potential assignments. -/
theorem valid_structured_source_generates_valid_assignment
    (source : StructuredScalarPotentialSource)
    (hSource : StructuredScalarPotentialSourceValid source) :
    DocumentPotentialAssignmentValid
      (certificateGeneratedAssignment (certificateFromStructuredSource source)) := by
  rcases hSource with ⟨hQuadraticToken, hRemainderToken⟩
  unfold DocumentPotentialAssignmentValid
  constructor
  · calc
    classifyDocumentTerm
      (certificateGeneratedAssignment (certificateFromStructuredSource source)).quadraticToken =
      classifyDocumentTerm source.quadraticToken := rfl
    _ = classifyDocumentTerm DocumentTermToken.scalarPotentialQuadratic := by
      simpa [hQuadraticToken]
    _ = DocumentTermClass.scalarMass := rfl
  · calc
    classifyDocumentTerm
      (certificateGeneratedAssignment (certificateFromStructuredSource source)).remainderToken =
      classifyDocumentTerm source.remainderToken := rfl
    _ = classifyDocumentTerm DocumentTermToken.scalarInteractionRemainder := by
      simpa [hRemainderToken]
    _ = DocumentTermClass.interaction := rfl

/-- A valid certificate generates a valid document potential assignment. -/
theorem valid_certificate_generates_valid_assignment
    (certificate : ScalarPotentialAssignmentCertificate)
    (hValid : ScalarPotentialAssignmentCertificateValid certificate) :
    DocumentPotentialAssignmentValid (certificateGeneratedAssignment certificate) := by
  rcases hValid with ⟨hQuadraticClass, hRemainderClass, hQuadraticToken, hRemainderToken⟩
  unfold DocumentPotentialAssignmentValid
  exact ⟨by simpa [hQuadraticClass] using hQuadraticToken,
    by simpa [hRemainderClass] using hRemainderToken⟩

/--
The standard scalar-potential tokens form a valid document-level assignment for
any chosen split.
-/
theorem document_potential_assignment_valid_of_expected_tokens
    (split : PotentialSplit) :
    DocumentPotentialAssignmentValid
      { quadraticToken := DocumentTermToken.scalarPotentialQuadratic
        remainderToken := DocumentTermToken.scalarInteractionRemainder
        split := split } := by
  exact ⟨rfl, rfl⟩

/--
The standard scalar-potential tokens form a valid scalar-potential certificate
for any chosen split and source identifier.
-/
theorem standard_scalar_potential_certificate_valid
    (sourceSpecId : String)
    (split : PotentialSplit) :
    ScalarPotentialAssignmentCertificateValid
      { sourceSpecId := sourceSpecId
        quadraticToken := DocumentTermToken.scalarPotentialQuadratic
        quadraticClass := DocumentTermClass.scalarMass
        remainderToken := DocumentTermToken.scalarInteractionRemainder
        remainderClass := DocumentTermClass.interaction
        split := split } := by
  exact ⟨rfl, rfl, rfl, rfl⟩

/--
The scalar-potential contribution in the sign convention used by the continuum
scalar action.
-/
def scalarPotentialContribution {Point : Type}
    (integral : ContinuumField Point → Real)
    (phi : ContinuumField Point)
    (split : PotentialSplit) : Real :=
  (1 / 2 : Real) * split.effectiveQuadraticCoeff *
      ContinuumPair integral phi phi +
    split.nonlinearRemainder

/-- Quadratic free-scalar regime for the chosen potential split. -/
def QuadraticFreeScalarRegime
    (split : PotentialSplit)
    (massSq : Real) : Prop :=
  split.effectiveQuadraticCoeff = massSq ∧
    split.nonlinearRemainder = 0

/--
Under the quadratic free-scalar regime, the scalar potential contribution is
exactly the scalar mass term used by `ContinuumFirstVariation.Action`.
-/
theorem quadratic_regime_reduces_to_mass_term {Point : Type}
    (integral : ContinuumField Point → Real)
    (phi : ContinuumField Point)
    (split : PotentialSplit)
    (massSq : Real)
    (hRegime : QuadraticFreeScalarRegime split massSq) :
    scalarPotentialContribution integral phi split =
      (1 / 2 : Real) * massSq * ContinuumPair integral phi phi := by
  rcases hRegime with ⟨hCoeff, hRemainder⟩
  unfold scalarPotentialContribution
  rw [hCoeff, hRemainder]
  ring

/--
Document-level free-scalar decomposition built from an explicit potential
split. Excluded blocks remain zero because this object is only the bounded
free-scalar regime surface.
-/
def freeScalarDocumentDecomposition {Point : Type}
    (phi : ContinuumField Point)
    (split : PotentialSplit) :
    DocumentActionDecomposition Point where
  scalarField := phi
  scalarKineticCoeff := 1
  scalarMassCoeff := split.effectiveQuadraticCoeff
  geometryBlock := 0
  fermionMatterBlock := 0
  gaugeBlock := 0
  statisticalEntropyBlock := 0
  transportSupportBlock := 0
  retainedUnformalizedBlock := 0
  scalarInteractionBlock := split.nonlinearRemainder
  seamConstraintBlock := 0

/--
The document-level free-scalar decomposition can be built directly from an
explicit document-to-split assignment.
-/
def documentPotentialAssignmentDecomposition {Point : Type}
    (phi : ContinuumField Point)
    (assignment : DocumentPotentialAssignment) :
    DocumentActionDecomposition Point :=
  freeScalarDocumentDecomposition phi assignment.split

/-- The document potential assignment exposes the underlying split unchanged. -/
theorem document_potential_assignment_decomposition_uses_split {Point : Type}
    (phi : ContinuumField Point)
    (assignment : DocumentPotentialAssignment) :
    documentPotentialAssignmentDecomposition phi assignment =
      freeScalarDocumentDecomposition phi assignment.split := by
  rfl

/-- The free-scalar decomposition exposes the potential split unchanged. -/
theorem free_scalar_document_decomposition_uses_split {Point : Type}
    (phi : ContinuumField Point)
    (split : PotentialSplit) :
    (freeScalarDocumentDecomposition phi split).scalarMassCoeff =
        split.effectiveQuadraticCoeff ∧
      (freeScalarDocumentDecomposition phi split).scalarInteractionBlock =
        split.nonlinearRemainder := by
  exact ⟨rfl, rfl⟩

/--
If the potential split is quadratic in the free-scalar regime, the induced
document decomposition satisfies the corresponding `DocumentFreeScalarRegime`.
-/
theorem quadratic_regime_yields_document_free_scalar_regime {Point : Type}
    (phi : ContinuumField Point)
    (split : PotentialSplit)
    (massSq : Real)
    (hRegime : QuadraticFreeScalarRegime split massSq) :
    DocumentFreeScalarRegime
      (freeScalarDocumentDecomposition phi split) phi massSq := by
  rcases hRegime with ⟨hCoeff, hRemainder⟩
  refine
    { scalar_selected := ?_
      kinetic_fixed := ?_
      mass_fixed := ?_
      geometry_neutral := ?_
      fermion_matter_neutral := ?_
      gauge_neutral := ?_
      statistical_entropy_neutral := ?_
      transport_support_neutral := ?_
      retained_unformalized_neutral := ?_
      scalar_interaction_zero := ?_
      seam_constraint_inactive := ?_ }
  · rfl
  · rfl
  · exact hCoeff
  · rfl
  · rfl
  · rfl
  · rfl
  · rfl
  · rfl
  · exact hRemainder
  · rfl

end
end ScalarPotentialDecomposition
end QFT
end ToeFormal
