from __future__ import annotations

RESEARCH_MODE_v0 = True
RESEARCH_MODE_NAMESPACE_v0 = "formal.python.research"
RESEARCH_MODE_BOUNDARY_v0 = "RESEARCH_ONLY_NO_CANONICAL_MUTATION"
RESEARCH_MODE_LOOP_DISCIPLINE_v0 = "ONE_OBJECT_ONE_QUESTION_ONE_TEST_ONE_OUTPUT"