from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
PAPER_DRAFT = REPO_ROOT / "formal" / "docs" / "paper" / "PAPER_DRAFT_v0.md"


def _read(path: Path) -> str:
    assert path.exists(), f"Missing required artifact: {path.as_posix()}"
    return path.read_text(encoding="utf-8")


def test_paper_draft_contains_required_sections_and_alignment_tokens() -> None:
    text = _read(PAPER_DRAFT)
    required_sections = [
        "## 1. Scope And Non-Claims",
        "## 2. Model Primitives / Representation Lanes",
        "## 3. Variational Framework And First Variation",
        "## 4. Main Result: EL-From-First-Variation Route (`T-CONDITIONAL`)",
        "## 5. RAC: Role And Status (`P-POLICY`)",
        "## 6. Comparator Program Summary (`E-REPRO`) And Limits",
        "## 7. Open Obligations (`B-BLOCKED`) And Promotion Gates",
        "## 8. Reproducibility",
    ]
    for section in required_sections:
        assert section in text, f"Paper draft missing required section: {section}"

    required_tokens = [
        "No external truth claim",
        "`T-PROVED`",
        "`T-CONDITIONAL`",
        "`E-REPRO`",
        "`P-POLICY`",
        "`B-BLOCKED`",
        "FN-DERIVE_default_quotient_hAction_provenance_v0.md",
        "FN-DERIVE_default_quotient_hRAC_obligation_bundle_v0.md",
        "FN-DERIVE_default_quotient_bridge_discharge_object_v0.md",
        "LATEST_STATE_SNAPSHOT.txt",
        "TOE_CLAIM_SURFACE_v0.md",
        "PHYSICS_ROADMAP_v0.md",
        "PHYSICS_PAPER_OUTLINE_v0.md",
        "STRUCTURAL_CLOSENESS_MAP_v0.md",
        "ASSUMPTION_REGISTRY_v1.md",
        "TOE-QM-THM-01",
        "DERIVATION_TARGET_QM_MEASUREMENT_SEMANTICS_v0.md",
        "DERIVATION_TARGET_QM_EVOLUTION_OBJECT_v0.md",
        "DERIVATION_TARGET_QM_SYMMETRY_OBJECT_v0.md",
        "DERIVATION_TARGET_QFT_EVOLUTION_OBJECT_v0.md",
        "DERIVATION_TARGET_QFT_GAUGE_OBJECT_v0.md",
        "DERIVATION_TARGET_GR_GEOMETRY_OBJECT_v0.md",
        "DERIVATION_TARGET_GR_CONSERVATION_OBJECT_v0.md",
        "DERIVATION_TARGET_GR01_BRIDGE_PROMOTION_v0.md",
        "DERIVATION_TARGET_GR01_REGIME_PROMOTION_v0.md",
        "DERIVATION_TARGET_GR01_SCALING_PROMOTION_v0.md",
        "DERIVATION_TARGET_GR01_SYMMETRY_PROMOTION_v0.md",
        "DERIVATION_TARGET_GR01_END_TO_END_CLOSURE_v0.md",
        "GR01BridgePromotion.lean",
        "GR01ScalingPromotion.lean",
        "GR01SymmetryPromotion.lean",
        "GR01EndToEndClosure.lean",
        "WeakFieldRegimePredicate",
        "gr01_regime_predicate_under_uniform_bound",
        "WeakFieldScalingHierarchy",
        "HigherOrderTermsNegligible",
        "gr01_scaling_hierarchy_under_regime_predicate",
        "gr01_first_order_truncation_sound",
        "ProjectionMapWellFormedPredicate",
        "gr01_projection_map_well_formed_under_regime_predicate",
        "gr01_projection_map_well_formed",
        "gr01_discrete_residual_from_bridge_promotion_chain",
        "GR01EndToEndClosureBundle",
        "gr01_end_to_end_chain_bundle_under_promoted_assumptions",
        "gr01_end_to_end_poisson_equation_under_promoted_assumptions",
        "TARGET-GR01-REG-PROMO-PLAN",
        "TARGET-GR01-SCALING-PROMO-PLAN",
        "TARGET-GR01-SYM-PROMO-PLAN",
        "TARGET-GR01-END2END-CLOSURE-PLAN",
        "ASM-GR01-REG-01",
        "ASM-GR01-APP-01",
        "ASM-GR01-SYM-01",
        "QM/MeasurementSemantics.lean",
        "QM/EvolutionContract.lean",
        "QM/SymmetryContract.lean",
        "QFT/EvolutionContract.lean",
        "QFT/GaugeContract.lean",
        "GR/GeometryContract.lean",
        "GR/ConservationContract.lean",
        "qm_measurement_weights_normalized_under_assumptions",
        "qm_evolution_under_contract_assumptions",
        "qm_state_fixed_under_symmetry_contract_assumptions",
        "qft_evolution_under_contract_assumptions",
        "qft_gauge_invariance_under_contract_assumptions",
        "gr_metric_invariance_under_contract_assumptions",
        "gr_conservation_under_contract_assumptions",
        "Expectation",
        "ExpectedObservable",
        "QMStateEvolvesUnderContract",
        "StateFixedUnderSymmetryAction",
        "EvolvesUnderContract",
        "FieldFixedUnderGaugeAction",
        "ConservationLawUnderFlow",
        "expectation_add",
        "expectation_smul",
        "expectation_nonneg_of_nonneg_weights_and_observable",
        "expected_observable_nonneg_of_support_nonneg",
        "not a Born-rule claim",
        "no Schrodinger derivation claim",
        "no unitary dynamics recovery claim",
        "no QM interpretation claim",
        "no Schrodinger/Dirac/Klein-Gordon derivation claim",
        "no Standard Model dynamics claim",
        "no Standard Model claim",
        "no GR field-equation claim",
        "no Noether theorem derivation claim",
        "THEORY_SPEC_v1.md",
        "DERIVATION_TARGET_NEWTONIAN_LIMIT_v0.md",
        "TOE_GR01_THEOREM_SURFACE_v0.md",
        "TOE_GR01_PROJECTION_BRIDGE_SPEC_v0.md",
        "TOE_GR01_WEAK_FIELD_EXPANSION_NOTE_v0.md",
        "TOE_GR01_POTENTIAL_IDENTIFICATION_v0.md",
        "TOE_GR01_LAPLACIAN_EXTRACTION_v0.md",
        "TOE_GR01_ANALYTIC_DISCHARGE_v0.md",
        "TOE_GR01_ACTION_RAC_STANCE_v0.md",
        "DERIVATION_TARGET_GR01_3D_MAINSTREAM_CLASS_v0.md",
        "TARGET-GR01-3D-03-PLAN",
        "TARGET-GR01-BRIDGE-PROMO-PLAN",
        "ASM-GR01-APP-02",
        "TOE_GR01_KAPPA_CALIBRATION_v0.md",
        "toe_gr01_kappa_calibration_v0.json",
        "TOE-GR-01_kappa_calibration_v0.md",
        "WeakFieldPoissonLimit.lean",
        "TOE_GR01_weak_field_poisson_limit_under_default_quotient_assumptions",
        "ProjectionMapWellFormed",
        "WeakFieldTruncationSound",
        "ELImpliesDiscretePoissonResidual",
        "OperatorToDiscreteResidual",
        "mkWeakFieldProjectionFromCore",
        "PoissonEquation1D",
        "Separable3DMappingAssumptions",
        "poissonEquation3D_of_componentwise_poissonEquation1D_under_separable",
        "Lift1DTo3DMappingAssumptions",
        "poissonEquation3D_of_poissonEquation1D_under_lift_x_only",
        "TOE_GR01_CONSERVATION_COMPATIBILITY_v0.md",
        "No new comparator lanes are authorized until `TOE-GR-01` reaches derivation-grade closure.",
        "planning-only",
        "non-claim",
        "no promotion",
        "no comparator-lane authorization",
    ]
    for token in required_tokens:
        assert token in text, f"Paper draft missing required token: {token}"
