from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
PAPER_DOCS_DIR = REPO_ROOT / "formal" / "docs" / "paper"
STATE_DOC = REPO_ROOT / "State_of_the_Theory.md"
NEWTONIAN_TARGET_DOC = PAPER_DOCS_DIR / "DERIVATION_TARGET_NEWTONIAN_LIMIT_v0.md"
END2END_TARGET_DOC = PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_END_TO_END_CLOSURE_v0.md"
RESULTS_DOC = PAPER_DOCS_DIR / "RESULTS_TABLE_v0.md"
STRUCTURAL_MAP_DOC = PAPER_DOCS_DIR / "STRUCTURAL_CLOSENESS_MAP_v0.md"
ANALYTIC_DISCHARGE_DOC = PAPER_DOCS_DIR / "TOE_GR01_ANALYTIC_DISCHARGE_v0.md"
THEORY_SPEC_DOC = PAPER_DOCS_DIR / "THEORY_SPEC_v1.md"
SR_COVARIANCE_TARGET_DOC = PAPER_DOCS_DIR / "DERIVATION_TARGET_SR_COVARIANCE_OBJECT_v0.md"
EM_U1_TARGET_DOC = PAPER_DOCS_DIR / "DERIVATION_TARGET_EM_U1_MAXWELL_OBJECT_v0.md"
QM_EVOLUTION_TARGET_DOC = PAPER_DOCS_DIR / "DERIVATION_TARGET_QM_EVOLUTION_OBJECT_v0.md"
PHYSICS_ROADMAP_DOC = PAPER_DOCS_DIR / "PHYSICS_ROADMAP_v0.md"
PHYSICS_PAPER_OUTLINE_DOC = PAPER_DOCS_DIR / "PHYSICS_PAPER_OUTLINE_v0.md"
THEOREM_SURFACE_DOC = PAPER_DOCS_DIR / "TOE_GR01_THEOREM_SURFACE_v0.md"
PROJECTION_BRIDGE_SPEC_DOC = PAPER_DOCS_DIR / "TOE_GR01_PROJECTION_BRIDGE_SPEC_v0.md"
ACTION_RAC_STANCE_DOC = PAPER_DOCS_DIR / "TOE_GR01_ACTION_RAC_STANCE_v0.md"
GR01_CONSERVATION_COMPAT_DOC = PAPER_DOCS_DIR / "TOE_GR01_CONSERVATION_COMPATIBILITY_v0.md"
GR01_3D_MAINSTREAM_CLASS_TARGET_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_3D_MAINSTREAM_CLASS_v0.md"
)
GR01_3D_03_ATTEMPT_PACKAGE_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_3D_03_DISCHARGE_ATTEMPT_PACKAGE_v0.md"
)
GR01_3D_03_CLOSURE_PACKAGE_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_3D_03_CLOSURE_PACKAGE_v0.md"
)
GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0.md"
)
GR01_3D_POINT_SOURCE_CLASS_TARGET_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0.md"
)
GR01_DERIVATION_CHECKLIST_DOC = (
    PAPER_DOCS_DIR / "DERIVATION_TARGET_GR01_DERIVATION_GRADE_CHECKLIST_v0.md"
)
DERIVATION_COMPLETENESS_GATE_DOC = PAPER_DOCS_DIR / "DERIVATION_COMPLETENESS_GATE_v0.md"
GR01_CANONICAL_EQUIV_DOC = PAPER_DOCS_DIR / "TOE_GR01_CANONICAL_EQUIVALENCE_THEOREM_v0.md"


def test_paper_docs_do_not_contain_stale_gr01_blocker_phrases() -> None:
    assert PAPER_DOCS_DIR.exists(), f"Missing paper docs directory: {PAPER_DOCS_DIR.as_posix()}"
    banned_phrases = [
        "theorem-chain composition + analytic alignment",
        "end-to-end derivation-grade closure criteria",
        "dominant blocker is now end-to-end derivation-grade closure criteria",
        "canonical-equivalence theorem remains an explicit open discharge item",
    ]

    offenders: list[str] = []
    for path in sorted(PAPER_DOCS_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        lowered = text.lower()
        hit = [phrase for phrase in banned_phrases if phrase.lower() in lowered]
        if hit:
            offenders.append(
                f"{path.as_posix()}: " + ", ".join(hit)
            )

    assert offenders == [], (
        "Paper docs contain stale GR01 blocker phrasing:\n" + "\n".join(offenders)
    )


def test_post_cls_gr01_positive_anchor_phrases_are_present() -> None:
    required_tokens_by_doc = {
        NEWTONIAN_TARGET_DOC: [
            "Current dominant blocker (v4): derivation-grade analytic discharge package closure",
            "TARGET-GR01-DERIV-CHECKLIST-PLAN",
            "DERIVATION_TARGET_GR01_DERIVATION_GRADE_CHECKLIST_v0.md",
            "TARGET-GR01-3D-03-PLAN",
            "TARGET-GR01-3D-03-CLOSURE-PACKAGE-PLAN",
            "DERIVATION_TARGET_GR01_3D_03_CLOSURE_PACKAGE_v0.md",
            "TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN",
            "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0.md",
            "TOE-GR-3D-03",
            "DERIVATION_TARGET_GR01_3D_MAINSTREAM_CLASS_v0.md",
        ],
        END2END_TARGET_DOC: [
            "theorem-chain closure criteria are satisfied under frozen scope (`TOE-GR-CLS-01`)",
            "remaining blocker for `TOE-GR-01` is derivation-grade analytic discharge package closure",
            "DERIVATION_TARGET_GR01_DERIVATION_GRADE_CHECKLIST_v0.md",
        ],
        RESULTS_DOC: [
            "| TOE-GR-PLAN-08 | `P-POLICY` |",
            "theorem-chain closure audit work-order",
            "| TOE-GR-DER-02 | `B-BLOCKED` |",
            "theorem-chain closure are closed, and the remaining block is derivation-grade analytic discharge package closure",
            "| TOE-GR-3D-02 | `T-CONDITIONAL` |",
            "poissonEquation3D_of_componentwise_poissonEquation1D_under_separable",
            "| TOE-GR-3D-03 | `T-CONDITIONAL` |",
            "TARGET-GR01-3D-03-PLAN",
            "DERIVATION_TARGET_GR01_3D_MAINSTREAM_CLASS_v0.md",
            "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0.md",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "| TOE-GR-3D-PS-01 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_under_dirichlet_boundary",
            "| TOE-GR-3D-PS-02 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_domain_residual_characterization_under_dirichlet_boundary",
            "| TOE-GR-3D-PS-03 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_residual_discharge_under_dirichlet_boundary",
            "| TOE-GR-3D-PS-04 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_center_residual_defect_is_explicit_under_dirichlet_boundary",
            "| TOE-GR-3D-PS-05 | `T-CONDITIONAL` |",
            "SatisfiesDirichletPoissonSystemOnDomain",
            "PointSourceDirichletCandidateSolution",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_derived_from_dirichlet_system",
            "| TOE-GR-3D-PS-06 | `T-CONDITIONAL` |",
            "IsInteriorPoint",
            "SatisfiesDirichletLinearSystemOnDomain",
            "gr01_mainstream3d_point_source_system_satisfaction_from_linear_system",
            "| TOE-GR-3D-PS-07 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_candidate_exists_from_linear_system",
            "| TOE-GR-3D-PS-08 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_linear_system_satisfaction_from_operator_equation",
            "SatisfiesFiniteLinearOperatorEquationOnDomain",
            "OperatorEncodesDiscreteLaplacianOnInterior",
            "DirichletLinearOperator3D",
            "| TOE-GR-3D-PS-09 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_candidate_exists_from_operator_equation",
            "| TOE-GR-3D-PS-10 | `T-CONDITIONAL` |",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_from_operator_equation",
            "| TOE-GR-3D-PS-11 | `T-PROVED` |",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "| TOE-GR-3D-PS-12 | `T-PROVED` |",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "OperatorHasDirichletRightInverseOnDomain",
            "does not promote `TOE-GR-3D-03`",
            "| TOE-GR-CONS-01 | `B-BLOCKED` |",
            "DERIVATION_TARGET_GR01_DERIVATION_GRADE_CHECKLIST_v0.md",
        ],
        STRUCTURAL_MAP_DOC: [
            "| `PILLAR-GR` | derivation-grade discharge checklist (planning-pointer) | `P-POLICY` | `TARGET-GR01-DERIV-CHECKLIST-PLAN` |",
            "| `PILLAR-GR` | 3D weak-field mapping (separable) | `T-CONDITIONAL` | `TOE-GR-3D-02` |",
            "| `PILLAR-GR` | 3D weak-field mapping (mainstream-class gate) | `T-CONDITIONAL` | `TOE-GR-3D-03` |",
            "| `PILLAR-GR` | conservation compatibility (weak-field) | `B-BLOCKED` | `TOE-GR-CONS-01` |",
            "Frozen checklist target for scaffold-to-discharge upgrades and action/RAC retirement alignment under unchanged scope.",
            "- `TARGET-GR01-DERIV-CHECKLIST-PLAN`: GR01 derivation-grade discharge checklist surface",
            "- `TARGET-GR01-3D-03-PLAN`: mainstream-class 3D closure gate target",
            "- `TARGET-GR01-3D-POINT-SOURCE-PLAN`: Track B bounded point-source-class closure sub-target",
        ],
        ANALYTIC_DISCHARGE_DOC: [
            "end-to-end theorem-chain closure milestone is complete (`TOE-GR-CLS-01`)",
            "target ID: `TARGET-GR01-DERIV-CHECKLIST-PLAN`",
            "TOE-GR-3D-03",
            "TARGET-GR01-3D-03-PLAN",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0.md",
            "action/RAC retirement items remain explicitly blocked (`BLK-01`, `BLK-02`) at state level.",
            "## Function-Space / Regularity / Boundary Posture (v0)",
            "## Integration-By-Parts And Boundary-Term Handling (explicit v0 narrative)",
            "## Constants Normalization And Canonical Form Mapping (scoped)",
            "## Assumption Minimization Audit (v0 snapshot)",
            "## Assumption Minimization Delta (v0 closure step)",
            "assumption-minimization status: `DISCHARGED` (v0 discrete-only).",
            "## Literature Alignment Mapping (v0 discrete-only CLOSED)",
            "literature-alignment status: `DISCHARGED` (v0 discrete-only).",
            "canonical-equivalence theorem status: `DISCHARGED`",
            "publication-grade derivation completeness gate status is `CLOSED` (v0 discrete-only)",
            "TOE-GR01-EQUIV-01",
            "TOE_GR01_CANONICAL_EQUIVALENCE_THEOREM_v0.md",
        ],
        THEORY_SPEC_DOC: [
            "TOE-GR-01 weak-field derivation remains blocked on derivation-grade analytic discharge package closure",
            "with action/RAC retirement items still explicit.",
            "solver-elimination promotion rule (Track B):",
            "eliminate explicit candidate-field input (`Φ`)",
            "expose existential output (`∃ Φ` / `∃! Φ`)",
        ],
        SR_COVARIANCE_TARGET_DOC: [
            "TARGET-SR-COV-PLAN",
            "Lorentz transform object",
            "Unlock condition:",
            "`LOCKED` until `TARGET-GR01-DERIV-CHECKLIST-PLAN` is `CLOSED` in `PHYSICS_ROADMAP_v0.md`.",
        ],
        EM_U1_TARGET_DOC: [
            "TARGET-EM-U1-PLAN",
            "Gauge potential object",
            "Unlock condition:",
            "`LOCKED` until `TARGET-GR01-DERIV-CHECKLIST-PLAN` is `CLOSED` in `PHYSICS_ROADMAP_v0.md`.",
        ],
        QM_EVOLUTION_TARGET_DOC: [
            "TARGET-QM-EVOL-PLAN",
            "This artifact does not claim Schrodinger-equation derivation.",
            "No new comparator lanes are authorized by this target.",
        ],
        PHYSICS_ROADMAP_DOC: [
            "Post-GR01 unlock queue (frozen order intent):",
            "first unlock cohort: `PILLAR-SR` and `PILLAR-EM`",
            "Path 2 closure sprint lock (GR-only):",
            "do not unlock `PILLAR-QM`, `PILLAR-EM`, or `PILLAR-SR` while `TOE-GR-3D-03`",
            "`NOT_YET_DISCHARGED`",
            "TOE-GR-3D-02",
            "TOE-GR-3D-03",
            "TARGET-GR01-3D-03-PLAN",
            "TARGET-GR01-3D-03-ATTEMPT-PACKAGE-PLAN",
            "TARGET-GR01-3D-03-CLOSURE-PACKAGE-PLAN",
            "TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN",
            "TARGET-GR01-DERIV-COMPLETENESS-GATE-PLAN",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "DERIVATION_TARGET_GR01_3D_03_DISCHARGE_ATTEMPT_PACKAGE_v0.md",
            "DERIVATION_TARGET_GR01_3D_03_CLOSURE_PACKAGE_v0.md",
            "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0.md",
            "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0.md",
            "DERIVATION_COMPLETENESS_GATE_v0.md",
            "Derivation completeness gate semantics (publication-grade tier):",
            "DERIVATION_COMPLETENESS_GATE",
            "TOE-GR-CONS-01",
            "conditional-publish endpoint",
            "Blocker discharge-attempt semantics (active-pillar blockers):",
            "`B-AWAITING-DISCHARGE-ATTEMPT`",
            "`B-DISCHARGE-ATTEMPTED-BUT-UNPROVEN`",
            "Promotion attempt trigger and execution requirement:",
            "bounded attempt-package target/artifact pointer when the blocker is `TOE-GR-3D-03`",
            "closure-package target/artifact pointer when the blocker is `TOE-GR-3D-03`",
            "## Promotion Attempt Log",
            "Next promotion objective (token)",
            "`PILLAR-GR / TOE-GR-3D-03 (Track B)`",
            "`PILLAR-GR / TOE-GR-CONS-01`",
            "`TARGET-GR-CONS-PLAN`",
            "`formal/toe_formal/ToeFormal/GR/ConservationContract.lean`",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "gr_conservation_under_contract_assumptions",
        ],
        PHYSICS_PAPER_OUTLINE_DOC: [
            "PHYSICS_PAPER_OUTLINE_v0",
            "## 1. Model And Assumptions",
            "## 2. Derivation Chain (Primary Result)",
            "## 5. Falsifiability And Failure Modes",
            "## 7. Equivalence And Literature Mapping",
        ],
        ACTION_RAC_STANCE_DOC: [
            "TOE_GR01_ACTION_RAC_STANCE_v0",
            "Conservative conditional-derivation stance is selected.",
            "conditional-publish endpoint",
            "hAction",
            "hRAC",
            "Retirement Alignment Criteria",
            "TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN",
            "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0.md",
        ],
        GR01_CONSERVATION_COMPAT_DOC: [
            "TOE_GR01_CONSERVATION_COMPATIBILITY_v0",
            "Minimal Compatibility Statement",
            "nabla · g = -kappa * rho",
            "B-BLOCKED",
        ],
        GR01_3D_MAINSTREAM_CLASS_TARGET_DOC: [
            "DERIVATION_TARGET_GR01_3D_MAINSTREAM_CLASS_v0",
            "TARGET-GR01-3D-03-PLAN",
            "TARGET-GR01-3D-03-ATTEMPT-PACKAGE-PLAN",
            "DERIVATION_TARGET_GR01_3D_03_DISCHARGE_ATTEMPT_PACKAGE_v0.md",
            "TARGET-GR01-3D-03-CLOSURE-PACKAGE-PLAN",
            "DERIVATION_TARGET_GR01_3D_03_CLOSURE_PACKAGE_v0.md",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "TOE-GR-3D-03",
            "Spherical symmetry track",
            "Discrete Green-function / point-source track",
            "Contract-level boundary (explicit):",
            "`laplacian_reduces_to_radial` is currently an assumption field inside",
            "not a derived stencil-level lemma.",
            "## Track A Reduction Discharge Target (future upgrade; not yet satisfied)",
            "## Path 2 Closure Sprint (Track A first; bounded/discrete)",
            "gr01_mainstream3d_radial_poisson_away_from_source_from_operator_equation_under_spherical_symmetry",
            "gr01_mainstream3d_point_source_model_discrete_delta_or_shell",
            "gr01_mainstream3d_green_class_partial_surface_token",
            "SphericalOperatorEquationAwayFromSourceAssumptions",
            "operator_equation_3d_away_from_source",
            "radiusBound",
            "radial_index_realized_within_bound",
            "Track A green-class token must be derived from 3D operator-equation posture",
            "Track A contributes a mapping bridge",
            "PointSourceMappingAssumptions",
            "gr01_mainstream3d_point_source_bounded_potential_behavior_posture",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "gr01_mainstream3d_point_source_residual_discharge_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_center_residual_defect_is_explicit_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_domain_residual_characterization_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_under_dirichlet_boundary",
            "FiniteDirichletDomain3D",
            "IsInteriorPoint",
            "SatisfiesDirichletLinearSystemOnDomain",
            "SatisfiesDirichletPoissonSystemOnDomain",
            "DirichletLinearOperator3D",
            "DirichletRHS3D",
            "OperatorEncodesDiscreteLaplacianOnInterior",
            "SatisfiesFiniteLinearOperatorEquationOnDomain",
            "OperatorHasDirichletRightInverseOnDomain",
            "PointSourceDirichletCandidateSolution",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_derived_from_dirichlet_system",
            "gr01_mainstream3d_point_source_linear_system_satisfaction_from_operator_equation",
            "gr01_mainstream3d_point_source_system_satisfaction_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_operator_equation",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_from_operator_equation",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0.md",
            "Track B is bounded discrete posture only and is currently assumption-scoped.",
            "no continuum-limit or infinite-domain Green-function inversion claim is implied.",
            "B-BLOCKED",
        ],
        GR01_3D_03_ATTEMPT_PACKAGE_DOC: [
            "DERIVATION_TARGET_GR01_3D_03_DISCHARGE_ATTEMPT_PACKAGE_v0",
            "TARGET-GR01-3D-03-ATTEMPT-PACKAGE-PLAN",
            "## Required Attempt Deliverables (All Required Per Cycle)",
            "## Mandatory Failure Triggers",
            "missing promotion hypothesis.",
            "missing promotion mechanism.",
            "missing attempt cycle ID.",
            "missing objective theorem token in scaffold module.",
            "Discharge path defined = YES",
            "B-AWAITING-DISCHARGE-ATTEMPT",
            "## v0 Track B Attempt Package Snapshot",
            "PILLAR-GR / TOE-GR-3D-03 (Track B)",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "Cycle-002 (2026-02-14)",
            "B-DISCHARGE-ATTEMPTED-BUT-UNPROVEN",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "formal/toe_formal/ToeFormal/Variational/GR01Mainstream3DPointSource.lean",
            "does not promote `TOE-GR-3D-03` by itself.",
        ],
        GR01_3D_03_CLOSURE_PACKAGE_DOC: [
            "DERIVATION_TARGET_GR01_3D_03_CLOSURE_PACKAGE_v0",
            "TARGET-GR01-3D-03-CLOSURE-PACKAGE-PLAN",
            "## Closure Transition Rule (v0 bounded/discrete scope)",
            "## Required Closure-Package Deliverables (Path 2; all required)",
            "Closure adjudication status (machine-checkable; required before status change)",
            "Allowed adjudication values:",
            "NOT_YET_SATISFIED",
            "SATISFIED_v0_DISCRETE",
            "ADJUDICATION:",
            "## Mandatory Failure Triggers",
            "## Missing Closure Deliverables Blocking `SATISFIED_v0_DISCRETE` (v0)",
            "## Adjudication Justification (v0)",
            "`NOT_YET_SATISFIED` rationale:",
            "`SATISFIED_v0_DISCRETE` rationale template",
            "No missing closure deliverables remain for `SATISFIED_v0_DISCRETE`.",
            "gr01_mainstream3d_discrete_laplacian_reduces_to_radial_under_spherical_symmetry",
            "gr01_mainstream3d_radial_poisson_away_from_source_from_operator_equation_under_spherical_symmetry",
            "gr01_mainstream3d_point_source_model_discrete_delta_or_shell",
            "gr01_mainstream3d_green_class_partial_surface_token",
            "SphericalOperatorEquationAwayFromSourceAssumptions",
            "operator_equation_3d_away_from_source",
            "radiusBound",
            "radial_index_realized_within_bound",
            "Track A green-class token must be derived from 3D operator-equation posture,",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "does not by itself promote `TOE-GR-3D-03`.",
            "Current adjudication token (v0):",
            "ADJUDICATION: SATISFIED_v0_DISCRETE",
        ],
        GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_DOC: [
            "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0",
            "TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN",
            "## Required Alignment Deliverables (all required)",
            "## Mandatory Failure Triggers",
            "## Discharged Alignment Endpoint Definition (v0 conditional-publish posture)",
            "Alignment adjudication token (machine-checkable):",
            "ALIGNMENT_ADJUDICATION: <allowed value>",
            "ALIGNMENT_ADJUDICATION: NOT_YET_DISCHARGED",
            "conditional-publish endpoint",
            "hAction",
            "hRAC",
            "BLK-01",
            "BLK-02",
            "FN-DERIVE_default_quotient_hAction_provenance_v0.md",
            "FN-DERIVE_default_quotient_hRAC_obligation_bundle_v0.md",
            "FN-DERIVE_default_quotient_bridge_discharge_object_v0.md",
        ],
        GR01_3D_POINT_SOURCE_CLASS_TARGET_DOC: [
            "DERIVATION_TARGET_GR01_3D_POINT_SOURCE_CLASS_v0",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "PointSourceMappingAssumptions",
            "gr01_mainstream3d_point_source_delta_posture_is_explicit",
            "gr01_mainstream3d_point_source_bounded_domain_posture",
            "gr01_mainstream3d_point_source_bounded_potential_behavior_posture",
            "gr01_mainstream3d_point_source_poissonEquation3D_under_bounded_delta_posture",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "no continuum-limit claim.",
            "no infinite-domain inversion claim.",
            "no full fundamental-solution uniqueness claim.",
            "## Track B Residual Discharge Target (future upgrade; not yet satisfied)",
            "PointSourceDirichletBoundaryAssumptions",
            "gr01_mainstream3d_point_source_dirichlet_boundary_posture_is_explicit",
            "gr01_mainstream3d_point_source_residual_zero_away_from_source_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_center_residual_defect_is_explicit_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_residual_discharge_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_domain_residual_characterization_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_under_dirichlet_boundary",
            "FiniteDirichletDomain3D",
            "IsInteriorPoint",
            "SatisfiesDirichletLinearSystemOnDomain",
            "SatisfiesDirichletPoissonSystemOnDomain",
            "DirichletLinearOperator3D",
            "DirichletRHS3D",
            "OperatorEncodesDiscreteLaplacianOnInterior",
            "SatisfiesFiniteLinearOperatorEquationOnDomain",
            "OperatorHasDirichletRightInverseOnDomain",
            "PointSourceDirichletCandidateSolution",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_derived_from_dirichlet_system",
            "gr01_mainstream3d_point_source_linear_system_satisfaction_from_operator_equation",
            "gr01_mainstream3d_point_source_system_satisfaction_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_operator_equation",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_from_operator_equation",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
            "candidate potential class:",
            "boundary condition class:",
            "stencil residual endpoint lemma:",
            "GR01Mainstream3DPointSource.lean",
            "B-BLOCKED",
        ],
        THEOREM_SURFACE_DOC: [
            "TOE_GR01_THEOREM_SURFACE_v0",
            "contract-level boundary:",
            "mapping-assumption field (`laplacian_reduces_to_radial`), not a derived stencil theorem.",
            "gr01_mainstream3d_discrete_laplacian_reduces_to_radial_under_spherical_symmetry",
            "gr01_mainstream3d_discrete_residual_reduces_to_radial_under_spherical_symmetry",
            "gr01_mainstream3d_radial_poisson_away_from_source_from_operator_equation_under_spherical_symmetry",
            "gr01_mainstream3d_point_source_model_discrete_delta_or_shell",
            "gr01_mainstream3d_green_class_partial_surface_token",
            "SphericalOperatorEquationAwayFromSourceAssumptions",
            "operator_equation_3d_away_from_source",
            "radiusBound",
            "radial_index_realized_within_bound",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "gr01_mainstream3d_point_source_bounded_potential_behavior_posture",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "gr01_mainstream3d_point_source_residual_discharge_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_center_residual_defect_is_explicit_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_domain_residual_characterization_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_under_dirichlet_boundary",
            "FiniteDirichletDomain3D",
            "IsInteriorPoint",
            "SatisfiesDirichletLinearSystemOnDomain",
            "SatisfiesDirichletPoissonSystemOnDomain",
            "DirichletLinearOperator3D",
            "DirichletRHS3D",
            "OperatorEncodesDiscreteLaplacianOnInterior",
            "SatisfiesFiniteLinearOperatorEquationOnDomain",
            "OperatorHasDirichletRightInverseOnDomain",
            "PointSourceDirichletCandidateSolution",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_derived_from_dirichlet_system",
            "gr01_mainstream3d_point_source_linear_system_satisfaction_from_operator_equation",
            "gr01_mainstream3d_point_source_system_satisfaction_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_operator_equation",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_from_operator_equation",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
        ],
        PROJECTION_BRIDGE_SPEC_DOC: [
            "TOE_GR01_PROJECTION_BRIDGE_SPEC_v0",
            "Track A reduction status:",
            "contract assumption field;",
            "future-scoped.",
            "gr01_mainstream3d_discrete_laplacian_reduces_to_radial_under_spherical_symmetry",
            "gr01_mainstream3d_discrete_residual_reduces_to_radial_under_spherical_symmetry",
            "gr01_mainstream3d_radial_poisson_away_from_source_from_operator_equation_under_spherical_symmetry",
            "gr01_mainstream3d_point_source_model_discrete_delta_or_shell",
            "gr01_mainstream3d_green_class_partial_surface_token",
            "SphericalOperatorEquationAwayFromSourceAssumptions",
            "operator_equation_3d_away_from_source",
            "radiusBound",
            "radial_index_realized_within_bound",
            "TARGET-GR01-3D-POINT-SOURCE-PLAN",
            "gr01_mainstream3d_point_source_bounded_potential_behavior_posture",
            "gr01_mainstream3d_point_source_partial_surface_token",
            "gr01_mainstream3d_point_source_residual_discharge_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_center_residual_defect_is_explicit_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_domain_residual_characterization_under_dirichlet_boundary",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_under_dirichlet_boundary",
            "FiniteDirichletDomain3D",
            "IsInteriorPoint",
            "SatisfiesDirichletLinearSystemOnDomain",
            "SatisfiesDirichletPoissonSystemOnDomain",
            "DirichletLinearOperator3D",
            "DirichletRHS3D",
            "OperatorEncodesDiscreteLaplacianOnInterior",
            "SatisfiesFiniteLinearOperatorEquationOnDomain",
            "OperatorHasDirichletRightInverseOnDomain",
            "PointSourceDirichletCandidateSolution",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_derived_from_dirichlet_system",
            "gr01_mainstream3d_point_source_linear_system_satisfaction_from_operator_equation",
            "gr01_mainstream3d_point_source_system_satisfaction_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_linear_system",
            "gr01_mainstream3d_point_source_candidate_exists_from_operator_equation",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_from_operator_equation",
            "gr01_mainstream3d_point_source_solution_exists_for_operator_equation_under_invertibility",
            "gr01_mainstream3d_point_source_poissonEquation3D_away_from_source_exists_from_operator_equation_under_invertibility",
        ],
        STATE_DOC: [
            "Target ID: `TARGET-GR01-DERIV-CHECKLIST-PLAN`",
            "Target ID: `TARGET-GR01-3D-03-PLAN`",
            "Target ID: `TARGET-GR01-3D-03-ATTEMPT-PACKAGE-PLAN`",
            "Target ID: `TARGET-GR01-3D-03-CLOSURE-PACKAGE-PLAN`",
            "Target ID: `TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN`",
            "`TOE-GR-3D-03`",
            "dominant remaining blockers are explicit action/RAC retirement alignment plus conservation compatibility `TOE-GR-CONS-01`",
        ],
        PAPER_DOCS_DIR / "CLAIM_TAXONOMY_v0.md": [
            "Solver-elimination promotion rule (Track B, v0)",
            "eliminates explicit candidate-field theorem input",
            "exposes existential output (`∃ Φ` or `∃! Φ`)",
            "Publication-grade derivation gate rule (all pillars, v0 policy)",
            "`T-PROVED` is necessary but not sufficient for publication-grade derivation claims",
            "TARGET-GR01-DERIV-COMPLETENESS-GATE-PLAN",
            "DERIVATION_COMPLETENESS_GATE_v0.md",
        ],
        GR01_DERIVATION_CHECKLIST_DOC: [
            "TARGET-GR01-DERIV-COMPLETENESS-GATE-PLAN",
            "DERIVATION_COMPLETENESS_GATE_v0.md",
            "TARGET-GR01-ACTION-RAC-RETIREMENT-ALIGNMENT-PLAN",
            "DERIVATION_TARGET_GR01_ACTION_RAC_RETIREMENT_ALIGNMENT_v0.md",
            "Derivation completeness gate (publication-grade tier; required before publishable promotion):",
            "mainstream equivalence proof to canonical weak-field form `nabla^2 Phi = kappa * rho`",
            "assumption minimization audit",
            "literature alignment mapping",
        ],
        DERIVATION_COMPLETENESS_GATE_DOC: [
            "DERIVATION_COMPLETENESS_GATE_v0",
            "TARGET-GR01-DERIV-COMPLETENESS-GATE-PLAN",
            "Gate Layers (All Required)",
            "Analytic discharge completeness",
            "Mainstream equivalence proof",
            "TOE_GR01_CANONICAL_EQUIVALENCE_THEOREM_v0.md",
            "TOE-GR01-EQUIV-01",
            "Assumption minimization audit",
            "Literature alignment mapping",
            "Mandatory Failure Triggers",
            "missing integration-by-parts step",
            "missing boundary-term handling",
            "missing function-space/regularity class",
            "missing constants normalization/units mapping",
            "missing canonical equivalence theorem",
            "Current gate posture for GR01: `CLOSED` (v0 discrete-only).",
        ],
        GR01_CANONICAL_EQUIV_DOC: [
            "TOE_GR01_CANONICAL_EQUIVALENCE_THEOREM_v0",
            "TOE-GR01-EQUIV-01",
            "DiscreteLaplacian1D Φ i = κ * ρ i",
            "poissonEquation1D_iff_discreteLaplacian1D_eq_kappa_rho",
            "poissonEquation3D_iff_discreteLaplacian3D_eq_kappa_rho",
            "gr01_end_to_end_poisson_equation_under_promoted_assumptions",
            "canonical-equivalence theorem status: `DISCHARGED`",
        ],
    }

    for path, tokens in required_tokens_by_doc.items():
        assert path.exists(), f"Missing required anchor doc: {path.as_posix()}"
        text = path.read_text(encoding="utf-8")
        for token in tokens:
            assert token in text, (
                f"Missing post-CLS positive anchor token in {path.as_posix()}: {token}"
            )
