from __future__ import annotations

from pathlib import Path

from formal.python.meta.repo_environment import find_repo_root
from formal.python.tests.strict_physics_state_helpers import (
    assert_focused_gate_not_manifest_enrolled,
)


REPO_ROOT = find_repo_root(Path(__file__))
INDEX_PATH = (
    REPO_ROOT
    / "formal"
    / "docs"
    / "release"
    / "CURRENT_AUTHORITATIVE_SURFACES_v0.md"
)
REGISTRY_PATH = REPO_ROOT / "formal" / "docs" / "release" / "LOOP_CONTROL_REGISTRY_v0.json"
FRONTIER_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "CrossPillarClosureFrontier.lean"
)
HYGIENE_SURFACE_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "ReadOnlyValidationHygiene.lean"
)
POST_HYGIENE_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostReadOnlyValidationHygieneBoundedAttackSelection.lean"
)
AFTER_HYGIENE_FULL_PILLAR_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "FullPillarTargetMapNextLaneSelectionAfterReadOnlyHygiene.lean"
)
ARTIFACT_RETENTION_PLAN_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "ArtifactRetentionEnforcementPlan.lean"
)
ARTIFACT_RETENTION_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "ArtifactRetentionEnforcementPlanResultReview.lean"
)
POST_ARTIFACT_RETENTION_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostArtifactRetentionEnforcementBoundedAttackSelection.lean"
)
STATUS_SURFACE_CANONICALIZATION_PLAN_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "StatusSurfaceCanonicalizationPlan.lean"
)
STATUS_SURFACE_CANONICALIZATION_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "StatusSurfaceCanonicalizationPlanResultReview.lean"
)
POST_STATUS_SURFACE_CANONICALIZATION_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostStatusSurfaceCanonicalizationBoundedAttackSelection.lean"
)
STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "StatusSurfaceCanonicalizationEnforcementPacket.lean"
)
STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "StatusSurfaceCanonicalizationEnforcementPacketResultReview.lean"
)
POST_STATUS_SURFACE_ENFORCEMENT_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostStatusSurfaceEnforcementBoundedAttackSelection.lean"
)
AFTER_STATUS_SURFACE_ENFORCEMENT_FULL_PILLAR_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "FullPillarTargetMapNextLaneSelectionAfterStatusSurfaceEnforcement.lean"
)
NEXT_PROOF_DEBT_ITEM_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "NextProofDebtLedgerDischargeItem.lean"
)
SAMPLEREP32_DISCHARGE_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Variational"
    / "FNRepNonAliasEquivalence01SampleRep32Discharge.lean"
)
SAMPLEREP32_DISCHARGE_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Variational"
    / "FNRepNonAliasEquivalence01SampleRep32DischargeResultReview.lean"
)
POST_FNREP_SAMPLEREP32_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostFNRepSampleRep32DischargeBoundedAttackSelection.lean"
)
AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "AxiomLedgerAuditRefreshAfterSampleRep32.lean"
)
AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "AxiomLedgerAuditRefreshAfterSampleRep32ResultReview.lean"
)
POST_SAMPLEREP32_AXIOM_AUDIT_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostSampleRep32AxiomAuditBoundedAttackSelection.lean"
)
AFTER_SAMPLEREP32_AXIOM_AUDIT_FULL_PILLAR_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "FullPillarTargetMapNextLaneSelectionAfterSampleRep32AxiomAudit.lean"
)
QM_STAT_THEOREM_GAP_REENTRY_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatTheoremGapReentry.lean"
)
QM_STAT_THEOREM_GAP_REENTRY_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatTheoremGapReentryResultReview.lean"
)
QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatTargetStatEntropySemanticsTheoremGap.lean"
)
QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatTargetStatEntropySemanticsTheoremGapResultReview.lean"
)
POST_QM_STAT_ENTROPY_SEMANTICS_GAP_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostQMStatEntropySemanticsGapBoundedAttackSelection.lean"
)
AFTER_QM_STAT_ENTROPY_SEMANTICS_GAP_FULL_PILLAR_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "FullPillarTargetMapNextLaneSelectionAfterQMStatEntropySemanticsGap.lean"
)
QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatEntropySemanticsSupportingAssumptionMap.lean"
)
QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatEntropySemanticsSupportingAssumptionMapResultReview.lean"
)
POST_QM_STAT_ENTROPY_ASSUMPTION_MAP_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostQMStatEntropyAssumptionMapBoundedAttackSelection.lean"
)
QM_STAT_ENTROPY_ASSUMPTION_REDUCTION_CANDIDATE_SELECTION_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatEntropyAssumptionReductionCandidateSelection.lean"
)
QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_REDUCTION_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatEntropyLogDomainZeroHandlingReduction.lean"
)
QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_REDUCTION_RESULT_REVIEW_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "QMStatEntropyLogDomainZeroHandlingReductionResultReview.lean"
)
POST_QM_STAT_ENTROPY_LOG_DOMAIN_REDUCTION_SELECTOR_PATH = (
    REPO_ROOT
    / "formal"
    / "toe_formal"
    / "ToeFormal"
    / "Derivation"
    / "PostQMStatEntropyLogDomainReductionBoundedAttackSelection.lean"
)
LEDGER_PATH = REPO_ROOT / "formal" / "docs" / "release" / "LEAN_AXIOM_SPEC_BACKED_LEDGER_v0.md"


def _read(path: Path) -> str:
    assert path.exists(), f"Missing required file: {path}"
    return path.read_text(encoding="utf-8")


def test_current_authoritative_surfaces_index_records_live_authority_chain() -> None:
    text = _read(INDEX_PATH)

    for token in {
        "CURRENT_AUTHORITATIVE_SURFACES_v0",
            "CURRENT_LIVE_NEXT_TARGET_v0: authorize_toe_native_surrogate_v0_bounded_program",
            "PREVIOUS_LIVE_NEXT_TARGET_v0: select_qft_gr_quadratic_toe_role_after_generic_frozen_result_v0",
            "ACTIVE_LANE_v0: authorize_toe_native_surrogate_v0_bounded_program",
            "CURRENT_LIVE_TARGET_EVIDENCE_v0: formal/toe_formal/ToeFormal/Derivation/QFTGRQuadraticToeRoleAfterGenericFrozenResultV0.lean",
            "CURRENT_LIVE_TARGET_REPORT_v0: formal/docs/release/QFT_GR_QUADRATIC_TOE_ROLE_AFTER_GENERIC_FROZEN_RESULT_REVIEW_20260729_v0.json",
            "CURRENT_LIVE_TARGET_OUTCOME_v0: REFERENCE_CONTROL_ONLY_WITH_UNRESOLVED_AFTER_BOUNDED_ATTEMPT",
            "CURRENT_LIVE_TARGET_STRICT_OUTCOME_v0: QUADRATIC_PROGRAM_TERMINAL_REFERENCE_CONTROL_ONLY_NO_FURTHER_QUADRATIC_WORK_NATIVE_PROGRAM_REQUIRES_SEPARATE_AUTHORITY",
            "CURRENT_LIVE_TARGET_KIND_v0: toe_native_surrogate_v0_bounded_program_authorization",
        "Higher-Dimensional Curved-Background Scalar Guardrail",
        "V01_ALPHA_RELEASE_READINESS_ADJUDICATION_PACKET_RESULT_REVIEW_ACCEPTS_CRITICIZABILITY_ONLY_PACKET_AND_AUTHORIZES_READINESS_ADJUDICATION_EXECUTION_ONLY",
        "V01_ALPHA_RELEASE_READINESS_ADJUDICATION_AFTER_DEPENDENCY_REMEDIATION_CLOSEOUT_EXECUTED_WITH_NO_RELEASE_ASSEMBLY_OR_PROMOTION",
        "V01_ALPHA_CRITICIZABILITY_READINESS_ADJUDICATION_RESULT_REVIEW_ACCEPTS_ELIGIBILITY_AND_AUTHORIZES_QFT_GR_WITNESS_PACKET_PREPARATION_ONLY",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_PACKET_PREPARED_WITH_NO_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_PACKET_RESULT_REVIEW_ACCEPTS_WITNESS_PACKET_AND_AUTHORIZES_BOUNDED_WITNESS_ATTEMPT_ONLY",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_ATTEMPT_EXECUTED_WITH_NO_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_ATTEMPT_RESULT_REVIEW_ACCEPTS_OBSTRUCTION_AND_AUTHORIZES_REFINEMENT_PACKET_PREPARATION_ONLY",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_OBSTRUCTION_REFINEMENT_PACKET_PREPARED_WITH_NO_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_CONSERVED_RENORMALIZED_STRESS_ENERGY_SOURCE_WITNESS_OBSTRUCTION_REFINEMENT_RESULT_REVIEW_ACCEPTS_CONSERVATION_AS_PRIMARY_OBSTRUCTION_AND_AUTHORIZES_CONSERVATION_WITNESS_PACKET_PREPARATION_ONLY",
        "QFT_GR_STRESS_ENERGY_CONSERVATION_WITNESS_PACKET_PREPARED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_MASTER_ACTION_PROMOTION",
        "QFT_GR_STRESS_ENERGY_CONSERVATION_WITNESS_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_CONSERVATION_WITNESS_ATTEMPT_ONLY",
        "QFT_GR_STRESS_ENERGY_CONSERVATION_WITNESS_ATTEMPT_EXECUTED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_STRESS_ENERGY_CONSERVATION_WITNESS_ATTEMPT_RESULT_REVIEW_ACCEPTS_CONSERVATION_OBSTRUCTION_AND_AUTHORIZES_REFINEMENT_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITNESS_ATTEMPT_EXECUTED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITNESS_ATTEMPT_RESULT_REVIEW_ACCEPTS_OBSTRUCTION_AND_AUTHORIZES_REFINEMENT_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_OBSTRUCTION_REFINEMENT_PACKET_PREPARED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_COVARIANT_DERIVATIVE_OPERATOR_DOMAIN_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_COVARIANT_DERIVATIVE_OPERATOR_DOMAIN_PACKET_RESULT_REVIEW_ACCEPTS_OPERATOR_DOMAIN_PREPARATION_AND_AUTHORIZES_NEXT_BOUNDED_CONSERVATION_STATEMENT_PACKET_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_PACKET_RESULT_REVIEW_ACCEPTS_STATEMENT_FORMULATION_AND_AUTHORIZES_BOUNDED_CONSERVATION_WITNESS_ATTEMPT_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_WITNESS_ATTEMPT_EXECUTED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_WITNESS_ATTEMPT_RESULT_REVIEW_ACCEPTS_OBSTRUCTION_AND_AUTHORIZES_REFINEMENT_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_OBSTRUCTION_REFINEMENT_PACKET_PREPARED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_COVARIANT_CONSERVATION_STATEMENT_WITH_OPERATOR_DOMAIN_OBSTRUCTION_REFINEMENT_RESULT_REVIEW_ACCEPTS_MISSING_CONSERVATION_PROOF_OBJECT_AND_AUTHORIZES_PROOF_OBJECT_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_PROOF_OBJECT_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_COVARIANT_CONSERVATION_PROOF_OBJECT_PACKET_RESULT_REVIEW_ACCEPTS_PROOF_OBJECT_PREPARATION_AND_AUTHORIZES_BOUNDED_PROOF_OBJECT_ATTEMPT_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_PROOF_OBJECT_ATTEMPT_EXECUTED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_EMPIRICAL_VALIDATION",
        "QFT_GR_COVARIANT_CONSERVATION_PROOF_OBJECT_ATTEMPT_RESULT_REVIEW_ACCEPTS_PROOF_OBJECT_OBSTRUCTION_AND_AUTHORIZES_REFINEMENT_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_PROOF_OBJECT_OBSTRUCTION_REFINEMENT_RESULT_REVIEW_ACCEPTS_INSUFFICIENT_ASSUMPTIONS_BLOCKER_AND_AUTHORIZES_ASSUMPTION_REDUCTION_PACKET_PREPARATION_ONLY",
        "QFT_GR_COVARIANT_CONSERVATION_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_COVARIANT_CONSERVATION_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_ASSUMPTION_FAMILY_CLASSIFICATION_AND_AUTHORIZES_PRIMARY_ASSUMPTION_REDUCTION_TARGET_SELECTION_ONLY",
        "QFT_GR_OPERATOR_DOMAIN_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_OPERATOR_DOMAIN_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_OPERATOR_DOMAIN_REDUCTION_ANALYSIS_AND_AUTHORIZES_NEXT_BOUNDED_ASSUMPTION_TARGET_ONLY",
            "QFT_GR_SELECTED_OPERATOR_ACTION_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_ASSUMPTION_DISCHARGE_OR_SEAM_CLOSURE",
            "QFT_GR_SELECTED_OPERATOR_ACTION_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_SELECTED_OPERATOR_ACTION_ANALYSIS_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
            "QFT_GR_SELECTED_OPERATOR_ACTION_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
            "QFT_GR_SELECTED_OPERATOR_ACTION_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_OPERATOR_ACTION_ASSUMPTION_AND_AUTHORIZES_NEXT_OPERATOR_DOMAIN_ROW_SELECTION_ONLY",
            "QFT_GR_CANDIDATE_SOURCE_DOMAIN_MEMBERSHIP_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_SOURCE_ADMISSIBILITY_OR_SEAM_CLOSURE",
            "QFT_GR_CANDIDATE_SOURCE_DOMAIN_MEMBERSHIP_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
            "QFT_GR_CANDIDATE_SOURCE_DOMAIN_MEMBERSHIP_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_SOURCE_ADMISSIBILITY_OR_SEAM_CLOSURE",
            "QFT_GR_CANDIDATE_SOURCE_DOMAIN_MEMBERSHIP_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_SOURCE_DOMAIN_MEMBERSHIP_ASSUMPTION_AND_AUTHORIZES_NEXT_OPERATOR_DOMAIN_ROW_SELECTION_ONLY",
            "QFT_GR_STATE_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
            "QFT_GR_STATE_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
            "QFT_GR_STATE_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_SOURCE_ADMISSIBILITY_OR_SEAM_CLOSURE",
            "QFT_GR_STATE_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_STATE_EXPECTATION_DOMAIN_LINK_AND_AUTHORIZES_NEXT_OPERATOR_DOMAIN_ROW_SELECTION_ONLY",
            "QFT_GR_RENORMALIZED_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_SOURCE_ADMISSIBILITY_OR_SEAM_CLOSURE",
            "QFT_GR_RENORMALIZED_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
            "QFT_GR_RENORMALIZED_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_SOURCE_ADMISSIBILITY_OR_SEAM_CLOSURE",
            "QFT_GR_RENORMALIZED_EXPECTATION_DOMAIN_LINK_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_RENORMALIZED_EXPECTATION_DOMAIN_LINK_AND_AUTHORIZES_NEXT_OPERATOR_DOMAIN_ROW_SELECTION_ONLY",
            "QFT_GR_CONSERVATION_FORM_SCOPE_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
            "QFT_GR_CONSERVATION_FORM_SCOPE_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
            "QFT_GR_CONSERVATION_FORM_SCOPE_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
            "QFT_GR_CONSERVATION_FORM_SCOPE_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_CONSERVATION_FORM_SCOPE_AND_AUTHORIZES_NEXT_OPERATOR_DOMAIN_ROW_SELECTION_ONLY",
        "QFT_GR_METRIC_CONNECTION_SCOPE_ASSUMPTION_REDUCTION_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_METRIC_CONNECTION_SCOPE_ASSUMPTION_REDUCTION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_REDUCTION_ATTEMPT_ONLY",
        "QFT_GR_METRIC_CONNECTION_SCOPE_ASSUMPTION_REDUCTION_ATTEMPT_EXECUTED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_METRIC_CONNECTION_SCOPE_ASSUMPTION_REDUCTION_ATTEMPT_RESULT_REVIEW_ACCEPTS_REDUCED_METRIC_CONNECTION_SCOPE_AND_AUTHORIZES_OPERATOR_DOMAIN_ASSUMPTION_REDUCTION_CLOSEOUT_PREPARATION_ONLY",
        "QFT_GR_OPERATOR_DOMAIN_ASSUMPTION_REDUCTION_CLOSEOUT_PACKET_PREPARED_WITH_NO_CONSERVATION_WITNESS_OR_SEAM_CLOSURE",
        "QFT_GR_OPERATOR_DOMAIN_ASSUMPTION_REDUCTION_CLOSEOUT_RESULT_REVIEW_ACCEPTS_OPERATOR_DOMAIN_ROWS_AND_AUTHORIZES_NEXT_ASSUMPTION_FAMILY_SELECTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_FUTURE_REMEDIATION_PROGRAM_PREPARED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_FUTURE_REMEDIATION_PROGRAM_RESULT_REVIEW_ACCEPTS_REMEDIATION_PROGRAM_AND_SELECTS_NEXT_BOUNDED_ROUTE_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_BOUNDED_SOURCE_MAP_WITNESS_CHAIN_RESEARCH_PACKET_PREPARED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_BOUNDED_SOURCE_MAP_WITNESS_CHAIN_RESEARCH_PACKET_RESULT_REVIEW_ACCEPTS_RESEARCH_PACKET_AND_SELECTS_BOUNDED_NEXT_ACTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_BOUNDED_SOURCE_MAP_WITNESS_CHAIN_RESEARCH_ATTEMPT_EXECUTED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_BOUNDED_SOURCE_MAP_WITNESS_CHAIN_RESEARCH_ATTEMPT_RESULT_REVIEW_ACCEPTS_PARTIAL_CANDIDATE_AND_AUTHORIZES_CONSTRUCTION_PACKET_PREPARATION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_WITNESS_CHAIN_CONSTRUCTION_PACKET_FROM_RESEARCH_CANDIDATE_PREPARED_WITH_NO_WITNESS_CONSTRUCTION_OR_SOURCE_MAP_CLOSURE",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_WITNESS_CHAIN_CONSTRUCTION_PACKET_FROM_RESEARCH_CANDIDATE_RESULT_REVIEW_ACCEPTS_CONSTRUCTION_PACKET_AND_AUTHORIZES_BOUNDED_CONSTRUCTION_EXECUTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_WITNESS_CHAIN_CONSTRUCTION_FROM_RESEARCH_CANDIDATE_EXECUTED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_WITNESS_CHAIN_CONSTRUCTION_RESULT_REVIEW_ACCEPTS_WITNESS_CHAIN_CONSTRUCTION_AND_AUTHORIZES_SOURCE_MAP_AUTHORIZATION_ADJUDICATION_PACKET_PREPARATION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_AUTHORIZATION_ADJUDICATION_PACKET_PREPARED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_AUTHORIZATION_ADJUDICATION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_ADJUDICATION_EXECUTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_AUTHORIZATION_ADJUDICATION_EXECUTED_REQUIREMENTS_SATISFIED_PENDING_RESULT_REVIEW_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_AUTHORIZATION_ADJUDICATION_RESULT_REVIEW_ACCEPTS_REQUIREMENTS_SATISFIED_AND_AUTHORIZES_SOURCE_MAP_CLOSURE_ADJUDICATION_PREPARATION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_ADJUDICATION_PACKET_PREPARED_WITH_NO_SOURCE_MAP_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_ADJUDICATION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BOUNDED_CLOSURE_ADJUDICATION_EXECUTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_ADJUDICATION_EXECUTED_WITH_NO_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_ADJUDICATION_RESULT_REVIEW_ACCEPTS_SOURCE_MAP_CLOSURE_AUTHORIZATION_AND_AUTHORIZES_CLOSURE_REGISTRATION_PREPARATION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_REGISTRATION_PACKET_PREPARED_WITH_NO_SEAM_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_REGISTRATION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_CLOSURE_REGISTRATION_EXECUTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_REGISTRATION_EXECUTED_WITH_NO_QFT_GR_SEAM_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_SOURCE_MAP_CLOSURE_REGISTRATION_RESULT_REVIEW_ACCEPTS_REGISTERED_SOURCE_MAP_CLOSURE_AND_AUTHORIZES_TRANCHE_004_BLOCKER_MOVEMENT_PACKET_PREPARATION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_BLOCKER_MOVEMENT_REGISTRATION_PACKET_AFTER_SOURCE_MAP_CLOSURE_PREPARED_WITH_NO_SEAM_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_BLOCKER_MOVEMENT_REGISTRATION_PACKET_RESULT_REVIEW_ACCEPTS_PACKET_AND_AUTHORIZES_BLOCKER_MOVEMENT_EXECUTION_ONLY",
        "V01_ALPHA_RETAINED_TRANCHE_004_BLOCKER_MOVEMENT_REGISTERED_AFTER_SOURCE_MAP_CLOSURE_WITH_NO_SEAM_CLOSURE_OR_RELEASE_PROMOTION",
        "V01_ALPHA_RETAINED_TRANCHE_004_BLOCKER_MOVEMENT_REGISTRATION_RESULT_REVIEW_ACCEPTS_DOCUMENTED_SOURCE_MAP_CLOSED_NONBLOCKING_STATUS_AND_AUTHORIZES_DEPENDENCY_REMEDIATION_CLOSEOUT_PREPARATION_ONLY",
        "V01_ALPHA_DEPENDENCY_REMEDIATION_CLOSEOUT_PREPARED_AFTER_TRANCHE_004_MOVEMENT_WITH_NO_RELEASE_READINESS_OR_SEAM_PROMOTION",
        "V01_ALPHA_DEPENDENCY_REMEDIATION_CLOSEOUT_RESULT_REVIEW_ACCEPTS_ALL_TRANCHES_DOCUMENTED_NONBLOCKING_AND_AUTHORIZES_RELEASE_READINESS_ADJUDICATION_PREPARATION_ONLY",
                "CURRENT_LIVE_NEXT_TARGET_v0: authorize_toe_native_surrogate_v0_bounded_program",
                "PREVIOUS_LIVE_NEXT_TARGET_v0: select_qft_gr_quadratic_toe_role_after_generic_frozen_result_v0",
                "ACTIVE_LANE_v0: authorize_toe_native_surrogate_v0_bounded_program",
        "CURRENT_LIVE_TARGET_AUTHORITY_v0: formal/docs/release/LOOP_CONTROL_REGISTRY_v0.json",
        "CURRENT_LIVE_TARGET_FRONTIER_MIRROR_v0: formal/toe_formal/ToeFormal/Derivation/CrossPillarClosureFrontier.lean",
                "CURRENT_LIVE_TARGET_EVIDENCE_v0: formal/toe_formal/ToeFormal/Derivation/QFTGRQuadraticToeRoleAfterGenericFrozenResultV0.lean",
                "CURRENT_LIVE_TARGET_REPORT_v0: formal/docs/release/QFT_GR_QUADRATIC_TOE_ROLE_AFTER_GENERIC_FROZEN_RESULT_REVIEW_20260729_v0.json",
        "READ_ONLY_VALIDATION_HYGIENE_ENFORCED",
        "POST_READ_ONLY_VALIDATION_HYGIENE_NEXT_ATTACK_SELECTED",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTED_AFTER_READ_ONLY_HYGIENE",
        "ARTIFACT_RETENTION_ENFORCEMENT_PLAN_PREPARED",
        "ARTIFACT_RETENTION_ENFORCEMENT_PLAN_RESULT_REVIEW_CONSUMED",
        "POST_ARTIFACT_RETENTION_ENFORCEMENT_NEXT_ATTACK_SELECTED",
        "STATUS_SURFACE_CANONICALIZATION_PLAN_PREPARED",
        "STATUS_SURFACE_CANONICALIZATION_PLAN_RESULT_REVIEW_CONSUMED",
        "POST_STATUS_SURFACE_CANONICALIZATION_NEXT_ATTACK_SELECTED",
        "STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PACKET_PREPARED",
        "STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PACKET_RESULT_REVIEW_CONSUMED",
        "POST_STATUS_SURFACE_ENFORCEMENT_NEXT_ATTACK_SELECTED",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTED_AFTER_STATUS_SURFACE_ENFORCEMENT",
        "NEXT_PROOF_DEBT_LEDGER_DISCHARGE_ITEM_SELECTED",
        "FNREP_NONALIAS_SAMPLEREP32_DISCHARGED_LEAN_BACKED_CONSTRUCTOR",
        "FNREP_NONALIAS_SAMPLEREP32_DISCHARGE_RESULT_REVIEW_CONSUMED_LEAN_BACKED_CONSTRUCTOR",
        "POST_FNREP_SAMPLEREP32_DISCHARGE_NEXT_ATTACK_SELECTED",
        "AXIOM_LEDGER_AUDIT_REFRESH_CONFIRMED_59_REAL_AXIOMS",
        "AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_RESULT_REVIEW_CONSUMED_59_REAL_AXIOMS_CONFIRMED",
        "POST_SAMPLEREP32_AXIOM_AUDIT_NEXT_ATTACK_SELECTED",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTED_AFTER_SAMPLEREP32_AXIOM_AUDIT",
        "QM_STAT_THEOREM_GAP_REENTRY_PREPARED",
        "QM_STAT_THEOREM_GAP_REENTRY_RESULT_REVIEW_CONSUMED",
        "QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_SUPPLIED_ONLY",
        "QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_RESULT_REVIEW_CONSUMED_SUPPLIED_ONLY",
        "POST_QM_STAT_ENTROPY_SEMANTICS_GAP_NEXT_ATTACK_SELECTED",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTED_AFTER_QM_STAT_ENTROPY_SEMANTICS_GAP",
        "QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_PREPARED",
        "QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_RESULT_REVIEW_CONSUMED",
        "POST_QM_STAT_ENTROPY_ASSUMPTION_MAP_NEXT_ATTACK_SELECTED",
        "QM_STAT_ENTROPY_ASSUMPTION_REDUCTION_CANDIDATE_SELECTED",
        "QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_ASSUMPTION_REDUCED_LEAN_BACKED",
        "QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_REDUCTION_RESULT_REVIEW_CONSUMED_LEAN_BACKED",
        "POST_QM_STAT_ENTROPY_LOG_DOMAIN_REDUCTION_NEXT_ATTACK_SELECTED",
        "CANONICAL_CONTROL_SOURCES",
        "PUBLIC_SUMMARY_SURFACES",
        "ACTIVE_TARGET_MIRROR_SURFACES",
        "HISTORICAL_SUPERSEDED_SURFACES",
    }:
        assert token in text

    for path in {
        REGISTRY_PATH,
        FRONTIER_PATH,
        HYGIENE_SURFACE_PATH,
        POST_HYGIENE_SELECTOR_PATH,
        AFTER_HYGIENE_FULL_PILLAR_SELECTOR_PATH,
        ARTIFACT_RETENTION_PLAN_PATH,
        ARTIFACT_RETENTION_RESULT_REVIEW_PATH,
        POST_ARTIFACT_RETENTION_SELECTOR_PATH,
        STATUS_SURFACE_CANONICALIZATION_PLAN_PATH,
        STATUS_SURFACE_CANONICALIZATION_RESULT_REVIEW_PATH,
        POST_STATUS_SURFACE_CANONICALIZATION_SELECTOR_PATH,
        STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PATH,
        STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_RESULT_REVIEW_PATH,
        POST_STATUS_SURFACE_ENFORCEMENT_SELECTOR_PATH,
        AFTER_STATUS_SURFACE_ENFORCEMENT_FULL_PILLAR_SELECTOR_PATH,
        NEXT_PROOF_DEBT_ITEM_SELECTOR_PATH,
        SAMPLEREP32_DISCHARGE_PATH,
        SAMPLEREP32_DISCHARGE_RESULT_REVIEW_PATH,
        POST_FNREP_SAMPLEREP32_SELECTOR_PATH,
        AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_PATH,
        AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_RESULT_REVIEW_PATH,
        POST_SAMPLEREP32_AXIOM_AUDIT_SELECTOR_PATH,
        AFTER_SAMPLEREP32_AXIOM_AUDIT_FULL_PILLAR_SELECTOR_PATH,
        QM_STAT_THEOREM_GAP_REENTRY_PATH,
        QM_STAT_THEOREM_GAP_REENTRY_RESULT_REVIEW_PATH,
        QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_PATH,
        QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_RESULT_REVIEW_PATH,
        POST_QM_STAT_ENTROPY_SEMANTICS_GAP_SELECTOR_PATH,
        AFTER_QM_STAT_ENTROPY_SEMANTICS_GAP_FULL_PILLAR_SELECTOR_PATH,
        QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_PATH,
        QM_STAT_ENTROPY_SEMANTICS_SUPPORTING_ASSUMPTION_MAP_RESULT_REVIEW_PATH,
        POST_QM_STAT_ENTROPY_ASSUMPTION_MAP_SELECTOR_PATH,
        QM_STAT_ENTROPY_ASSUMPTION_REDUCTION_CANDIDATE_SELECTION_PATH,
        QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_REDUCTION_PATH,
        QM_STAT_ENTROPY_LOG_DOMAIN_ZERO_HANDLING_REDUCTION_RESULT_REVIEW_PATH,
        POST_QM_STAT_ENTROPY_LOG_DOMAIN_REDUCTION_SELECTOR_PATH,
        LEDGER_PATH,
    }:
        assert str(path.relative_to(REPO_ROOT)).replace("\\", "/") in text


def test_current_authoritative_surfaces_index_records_current_axiom_and_nonclaim_state() -> None:
    text = _read(INDEX_PATH)

    for token in {
        "REAL_AXIOM_COUNT_v0: 59",
        "REAL_SORRY_OR_ADMIT_COUNT_v0: 0",
        "defaultNonAlias: absent_from_unresolved_axiom_debt_and_lean_backed",
        "sampleRep32: absent_from_unresolved_axiom_debt_and_lean_backed_constructor",
        "QFT_GR_SOURCE_MAP_CLOSURE_AUTHORIZED_v0: false",
        "MASTER_ACTION_PROMOTION_AUTHORIZED_v0: false",
        "PILLAR_COMPLETION_INFERRED_v0: false",
        "SEAM_CLOSURE_CLAIM_v0: false",
        "PHASE2_READINESS_CLAIM_v0: false",
        "EMPIRICAL_ADEQUACY_CLAIM_v0: false",
        "CANONICAL_TOE_CLAIM_v0: false",
    }:
        assert token in text


def test_current_authoritative_surfaces_index_records_validation_and_historical_classes() -> None:
    text = _read(INDEX_PATH)

    for token in {
        ".\\run_governance.ps1",
        ".\\run_pytest.ps1",
        ".\\run_lean.ps1",
        "git diff --check",
        "Manual fallback validation commands",
        "pwsh -NoProfile -ExecutionPolicy Bypass -File ./governance_suite.ps1",
        "./py.ps1 -m pytest formal/python/tests -q",
        "Push-Location formal/toe_formal; lake build ToeFormal; Pop-Location",
        "git diff --exit-code",
        "formal/tooling_snapshots",
        "scratch",
        "archive",
        "backup",
        "REPOSITORY_ARTIFACT_RETENTION_POLICY_20260505_v0",
        "POST_READ_ONLY_VALIDATION_HYGIENE_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTION_AFTER_READ_ONLY_HYGIENE_20260505_v0",
        "ARTIFACT_RETENTION_ENFORCEMENT_PLAN_20260505_v0",
        "ARTIFACT_RETENTION_ENFORCEMENT_PLAN_RESULT_REVIEW_20260505_v0",
        "POST_ARTIFACT_RETENTION_ENFORCEMENT_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "STATUS_SURFACE_CANONICALIZATION_PLAN_20260505_v0",
        "STATUS_SURFACE_CANONICALIZATION_PLAN_RESULT_REVIEW_20260505_v0",
        "POST_STATUS_SURFACE_CANONICALIZATION_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PACKET_20260505_v0",
        "STATUS_SURFACE_CANONICALIZATION_ENFORCEMENT_PACKET_RESULT_REVIEW_20260505_v0",
        "POST_STATUS_SURFACE_ENFORCEMENT_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTION_AFTER_STATUS_SURFACE_ENFORCEMENT_20260508_v0",
        "NEXT_PROOF_DEBT_LEDGER_DISCHARGE_ITEM_20260505_v0",
        "PROOF_DEBT_DISCHARGE_FNREP_SAMPLEREP32_20260505_v0",
        "PROOF_DEBT_DISCHARGE_FNREP_SAMPLEREP32_RESULT_REVIEW_20260505_v0",
        "POST_FNREP_SAMPLEREP32_DISCHARGE_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_20260505_v0",
        "AXIOM_LEDGER_AUDIT_REFRESH_AFTER_SAMPLEREP32_RESULT_REVIEW_20260505_v0",
        "POST_SAMPLEREP32_AXIOM_AUDIT_BOUNDED_ATTACK_SELECTION_20260505_v0",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTION_AFTER_SAMPLEREP32_AXIOM_AUDIT_20260510_v0",
        "QM_STAT_THEOREM_GAP_REENTRY_20260510_v0",
        "QM_STAT_THEOREM_GAP_REENTRY_RESULT_REVIEW_20260510_v0",
        "QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_BOUNDED_ATTACK_20260510_v0",
        "QM_STAT_TARGET_STAT_ENTROPY_SEMANTICS_THEOREM_GAP_RESULT_REVIEW_20260510_v0",
        "POST_QM_STAT_ENTROPY_SEMANTICS_GAP_BOUNDED_ATTACK_SELECTION_20260510_v0",
        "FULL_PILLAR_TARGET_MAP_NEXT_LANE_SELECTION_AFTER_QM_STAT_ENTROPY_SEMANTICS_GAP_20260510_v0",
        "TOE_ALLOW_TRACKED_OUTPUT_WRITES=1",
    }:
        assert token in text


def test_current_authoritative_surfaces_gate_not_manifest_enrolled() -> None:
    assert_focused_gate_not_manifest_enrolled(
        "formal/python/tests/test_current_authoritative_surfaces_gate.py"
    )
