from __future__ import annotations

from pathlib import Path


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


CYCLE81_GATE_TOKEN = (
    "QFT_FULL_DERIVATION_PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_GATE_v0: "
    "REQUIRE_PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_AND_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_NONFLIP_CONFIRMATION"
)


def test_cycle81_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_tokens_in_discharge_doc() -> None:
    doc = _read(
        Path("formal/docs/paper/DERIVATION_TARGET_QFT_FULL_DERIVATION_DISCHARGE_v0.md")
    )
    assert (
        "QFT_FULL_DERIVATION_PROGRESS_CYCLE81_v0: "
        "PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_LOCK_PINNED" in doc
    )
    assert CYCLE81_GATE_TOKEN in doc
    assert (
        "QFT_FULL_DERIVATION_PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_SCOPE_v0: "
        "PREEXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_MAINTAINS_NONFLIP_EXECUTION_AND_NO_ADJUDICATION_FLIP" in doc
    )
    assert (
        "QFT_FULL_DERIVATION_PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_ARTIFACT_v0: "
        "qft_full_derivation_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_cycle81_v0" in doc
    )
    assert (
        "formal/output/"
        "qft_full_derivation_cycle81_v0.json" in doc
    )


def test_cycle81_practical_action_plan_tokens_present() -> None:
    doc = _read(Path("formal/docs/paper/DERIVATION_TARGET_QFT_FULL_DERIVATION_DISCHARGE_v0.md"))
    required = [
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_CYCLE81_v0: PREREQUISITE_AUTHORIZATION_GUARD_EXECUTION_PLAN_PINNED",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_PHASE1_v0: CYCLE27_31_CRITERIA_REVALIDATION_AND_EVIDENCE_LOCK_CHECKLIST",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_PHASE2_v0: CYCLE32_34_EXPLICIT_AUTHORIZATION_REPLAY_AND_TWO_KEY_STATUS_RECONCILIATION",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_PHASE3_v0: CYCLE35_EXECUTION_GUARD_ENFORCEMENT_AND_NONPENDING_ASSERTION",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_PHASE4_v0: CYCLE36_PLUS_NONFLIP_REVALIDATION_AND_READINESS_REPLAY_NO_ADJUDICATION_FLIP",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_GUARDRAIL_v0: ADJUDICATION_REMAINS_NOT_YET_DISCHARGED_UNTIL_EXPLICIT_TWO_KEY_AUTHORIZED_NONPENDING_GATE_CLOSURE",
        "formal/output/qft_full_derivation_discharge_practical_action_plan_cycle81_v0.json",
    ]
    for token in required:
        assert token in doc


def test_cycle81_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_tokens_in_state_and_roadmap() -> None:
    state = _read(Path("State_of_the_Theory.md"))
    roadmap = _read(Path("formal/docs/paper/PHYSICS_ROADMAP_v0.md"))

    required = [
        "QFT_FULL_DERIVATION_PROGRESS_CYCLE81_v0: PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_LOCK_PINNED",
        CYCLE81_GATE_TOKEN,
        "QFT_FULL_DERIVATION_PREEXECUTION_NONFLIP_EXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_SCOPE_v0: PREEXECUTION_CUSTODY_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_ATTESTATION_CONFIRMATION_PACKET_MAINTAINS_NONFLIP_EXECUTION_AND_NO_ADJUDICATION_FLIP",
        "formal/python/tests/test_qft_full_derivation_cycle81_gate.py",
        "QFT_FULL_DERIVATION_DISCHARGE_PRACTICAL_ACTION_PLAN_CYCLE81_v0: PREREQUISITE_AUTHORIZATION_GUARD_EXECUTION_PLAN_PINNED",
        "formal/output/qft_full_derivation_discharge_practical_action_plan_cycle81_v0.json",
    ]
    for token in required:
        assert token in state
        assert token in roadmap


def test_cycle81_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_preserves_nonflip_adjudication_tokens() -> None:
    doc = _read(Path("formal/docs/paper/DERIVATION_TARGET_QFT_FULL_DERIVATION_DISCHARGE_v0.md"))
    assert CYCLE81_GATE_TOKEN in doc
    assert "QFT_FULL_DERIVATION_ADJUDICATION_EXECUTION_GUARD_GATE_v0: FLIP_FORBIDDEN_UNLESS_TWO_KEY_AUTHORIZED_AND_NONPENDING" in doc
    assert "QFT_FULL_DERIVATION_MANUAL_FLIP_AUTHORIZATION_STATUS_GATE_v0: KEYA_KEYB_MUST_BE_AUTHORIZED" in doc
    assert "QFT_FULL_DERIVATION_ADJUDICATION: NOT_YET_DISCHARGED" in doc


def test_cycle81_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_artifact_json_exists_and_is_consistent() -> None:
    artifact = _read(
        Path(
            "formal/output/"
            "qft_full_derivation_cycle81_v0.json"
        )
    )
    assert '"artifact_id": "qft_full_derivation_preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_cycle81_v0"' in artifact
    assert '"cycle": 81' in artifact
    assert '"status": "preexecution_nonflip_execution_custody_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_attestation_confirmation_packet_locked"' in artifact
    assert '"token_write_allowed": false' in artifact
    assert '"adjudication_token_state_verified": "NOT_YET_DISCHARGED"' in artifact
