from __future__ import annotations

from pathlib import Path


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    while p != p.parent:
        if (p / "formal").exists():
            return p
        p = p.parent
    raise RuntimeError("Could not locate repo root (expected a 'formal' directory).")


REPO_ROOT = find_repo_root(Path(__file__))
QFT_EVOL_TARGET_PATH = REPO_ROOT / "formal" / "docs" / "paper" / "DERIVATION_TARGET_QFT_EVOLUTION_OBJECT_v0.md"
ROADMAP_PATH = REPO_ROOT / "formal" / "docs" / "paper" / "PHYSICS_ROADMAP_v0.md"
STATE_PATH = REPO_ROOT / "State_of_the_Theory.md"
TRANCHE_GATE_PATH = "formal/python/tests/test_qft_evol_micro_tranche_01_43_completeness_gate.py"
LEGACY_TRANCHE_GATE_PATH = "formal/python/tests/test_qft_evol_micro_tranche_01_42_completeness_gate.py"

TRANCHE_ORDERED_TOKENS = [
    "TARGET-QFT-EVOL-MICRO-01-TIME-STATE-OPERATOR-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_01_TIME_STATE_OPERATOR_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro01_time_state_operator_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-02-EVOLUTION-CONTEXT-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_02_EVOLUTION_CONTEXT_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro02_evolution_context_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-03-ACTION-DENSITY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_03_ACTION_DENSITY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro03_action_density_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-04-EULER-LAGRANGE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_04_EULER_LAGRANGE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro04_euler_lagrange_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-05-UNITARITY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_05_UNITARITY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro05_unitarity_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-06-CANONICAL-MOMENTUM-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_06_CANONICAL_MOMENTUM_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro06_canonical_momentum_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-07-EVOLUTION-GENERATOR-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_07_EVOLUTION_GENERATOR_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro07_evolution_generator_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-08-HAMILTONIAN-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_08_HAMILTONIAN_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro08_hamiltonian_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-09-HAMILTONIAN-GENERATOR-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_09_HAMILTONIAN_GENERATOR_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro09_hamiltonian_generator_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-10-EVOLUTION-CONTRACT-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_10_EVOLUTION_CONTRACT_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro10_evolution_contract_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-11-EVOLVES-UNDER-CONTRACT-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_11_EVOLVES_UNDER_CONTRACT_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro11_evolves_under_contract_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-12-QFT-EVOLUTION-UNDER-CONTRACT-ASSUMPTIONS-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_12_QFT_EVOLUTION_UNDER_CONTRACT_ASSUMPTIONS_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro12_qft_evolution_under_contract_assumptions_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-13-QFT-EVOLUTION-CONTRACT-THEOREM-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_13_QFT_EVOLUTION_CONTRACT_THEOREM_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro13_qft_evolution_contract_theorem_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-14-QFT-EVOLUTION-THEOREM-TOKEN-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_14_QFT_EVOLUTION_THEOREM_TOKEN_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro14_qft_evolution_theorem_token_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-15-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_15_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro15_qft_evolution_theorem_token_consumer_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-16-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-INTERFACE-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_16_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_INTERFACE_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro16_qft_evolution_theorem_token_consumer_binding_interface_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-17-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_17_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro17_qft_evolution_theorem_token_consumer_binding_compatibility_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-18-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_18_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro18_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-19-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_19_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro19_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-20-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_20_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro20_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-21-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_21_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro21_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-22-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_22_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro22_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-23-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_23_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro23_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-24-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_24_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro24_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-25-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_25_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro25_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-26-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_26_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro26_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-27-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_27_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro27_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-28-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_28_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro28_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-29-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_29_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro29_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-30-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_30_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro30_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-31-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_31_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_CONSUMER_CONSISTENCY_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro31_qft_evolution_theorem_token_consumer_binding_compatibility_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_consumer_consistency_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-32-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_32_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro32_qft_evolution_theorem_token_consumer_binding_compatibility_chain_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-33-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_33_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN2_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro33_qft_evolution_theorem_token_consumer_binding_compatibility_chain2_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-34-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_34_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN3_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro34_qft_evolution_theorem_token_consumer_binding_compatibility_chain3_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-35-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_35_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN4_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro35_qft_evolution_theorem_token_consumer_binding_compatibility_chain4_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-36-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_36_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN5_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro36_qft_evolution_theorem_token_consumer_binding_compatibility_chain5_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-37-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_37_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN6_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro37_qft_evolution_theorem_token_consumer_binding_compatibility_chain6_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-38-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_38_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN7_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro38_qft_evolution_theorem_token_consumer_binding_compatibility_chain7_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-39-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_39_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN8_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro39_qft_evolution_theorem_token_consumer_binding_compatibility_chain8_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-40-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_40_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN9_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro40_qft_evolution_theorem_token_consumer_binding_compatibility_chain9_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-41-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_41_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN10_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro41_qft_evolution_theorem_token_consumer_binding_compatibility_chain10_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-42-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_42_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN11_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro42_qft_evolution_theorem_token_consumer_binding_compatibility_chain11_surface_gate.py",
    "TARGET-QFT-EVOL-MICRO-43-QFT-EVOLUTION-THEOREM-TOKEN-CONSUMER-BINDING-COMPATIBILITY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-CONSUMER-CONSISTENCY-SURFACE-v0",
    "formal/docs/paper/DERIVATION_TARGET_QFT_EVOL_MICRO_43_QFT_EVOLUTION_THEOREM_TOKEN_CONSUMER_BINDING_COMPATIBILITY_CHAIN12_SURFACE_v0.md",
    "formal/python/tests/test_qft_evol_micro43_qft_evolution_theorem_token_consumer_binding_compatibility_chain12_surface_gate.py",
]


def _read(path: Path) -> str:
    assert path.exists(), f"Missing required file: {path}"
    return path.read_text(encoding="utf-8")


def _assert_present_in_order(text: str, ordered_tokens: list[str]) -> None:
    idx = -1
    for token in ordered_tokens:
        next_idx = text.find(token, idx + 1)
        assert next_idx >= 0, f"Missing ordered tranche token `{token}` in QFT evolution umbrella target."
        assert next_idx > idx, f"Out-of-order tranche token `{token}` in QFT evolution umbrella target."
        idx = next_idx


def test_qft_evol_micro_tranche_artifacts_exist() -> None:
    assert QFT_EVOL_TARGET_PATH.exists(), "Missing QFT evolution umbrella target document."
    assert ROADMAP_PATH.exists(), "Missing PHYSICS roadmap document."
    assert STATE_PATH.exists(), "Missing state checkpoint document."


def test_qft_evol_umbrella_contains_micro_tranche_01_43_in_order() -> None:
    text = _read(QFT_EVOL_TARGET_PATH)
    _assert_present_in_order(text, TRANCHE_ORDERED_TOKENS)


def test_qft_evol_micro_tranche_gate_is_pinned_in_authority_surfaces() -> None:
    roadmap_text = _read(ROADMAP_PATH)
    state_text = _read(STATE_PATH)

    assert TRANCHE_GATE_PATH in roadmap_text, (
        f"Roadmap authority surface must pin `{TRANCHE_GATE_PATH}`."
    )
    assert TRANCHE_GATE_PATH in state_text, (
        f"State authority surface must pin `{TRANCHE_GATE_PATH}`."
    )
    assert LEGACY_TRANCHE_GATE_PATH not in roadmap_text, (
        f"Roadmap authority surface must not pin legacy `{LEGACY_TRANCHE_GATE_PATH}`."
    )
    assert LEGACY_TRANCHE_GATE_PATH not in state_text, (
        f"State authority surface must not pin legacy `{LEGACY_TRANCHE_GATE_PATH}`."
    )















