from __future__ import annotations

from qm_stat_class_b_synthesis_gate_family_helper import QmStatSynthesisGateSpec, register_qm_stat_synthesis_gate_suite


register_qm_stat_synthesis_gate_suite(
    globals(),
    QmStatSynthesisGateSpec(
        cycle_from=9,
        cycle_to=10,
        required_doc_tokens=(
            "QM_STAT_CYCLE09_BASELINE_v0: FOURTEENTH_CENTRAL_MOMENT_PARITY_AND_EXCLUSION_PINNED",
            "QM_STAT_CYCLE10_ADDITIVE_DELTA_v0: SIXTEENTH_CENTRAL_MOMENT_PARITY_AND_EXCLUSION_PINNED",
            "QM_STAT_BLOCKER_DISCHARGE_IMPACT_v0: CRITERIA_STRENGTHENED_BUT_ADJUDICATION_STILL_OPEN",
            "QM_STAT_PROMOTION_BLOCKER_STATE_v0: CLASS_FLIP_AND_FULL_THEOREM_DISCHARGE_NOT_READY",
            "QM_STAT_NONCLAIM_BOUNDARY_STATE_v0: CLASS_FLIP_AND_FULL_DISCHARGE_NOT_CLAIMED",
            "QM_STAT_NEXT_DECISION_RULE_v0: IF_ONE_BOUNDED_ADDITIVE_QM_STAT_PAYLOAD_IS_READY_THEN_CONTINUE_CYCLE10_ELSE_STOP_AT_CYCLE09_TO_10_SYNTHESIS_BOUNDARY",
            "QM_STAT_DECISION_BOUNDARY_STATUS_v0: SYNTHESIS_CHECKPOINT_READY",
            "QM_STAT_NON_ACTIVE_LANE_ASSERTION_v0: COSMO_SR_REMAINS_PAUSED_UNLESS_EXPLICIT_ADDITIVE_PAYLOAD_DECLARATION",
            "QM_STAT_CLASS_B_SEAM_PHYSICS_PILOT_CYCLE09_TO_10_SYNTHESIS_STATUS_v0: CHECKPOINT_PINNED_NONCLAIM",
            "QM_STAT_CLASS_B_SEAM_PHYSICS_PILOT_CYCLE09_TO_10_SYNTHESIS_ADJUDICATION: NOT_YET_DISCHARGED",
        ),
        from_artifact_status="CRITERIA_AND_FOURTEENTH_MOMENT_EXCLUSION_PINNED_NONCLAIM",
        to_artifact_status="CRITERIA_AND_SIXTEENTH_MOMENT_EXCLUSION_PINNED_NONCLAIM",
        from_criteria_token="MASS_MEAN_VARIANCE_THIRD_FOURTH_SIXTH_EIGHTH_TENTH_TWELFTH_AND_FOURTEENTH_MOMENT_PARITY_REQUIRED",
        to_criteria_token="MASS_MEAN_VARIANCE_THIRD_FOURTH_SIXTH_EIGHTH_TENTH_TWELFTH_FOURTEENTH_AND_SIXTEENTH_MOMENT_PARITY_REQUIRED",
        from_criteria_orders=(1, 2, 3, 4, 6, 8, 10, 12, 14),
        to_criteria_orders=(1, 2, 3, 4, 6, 8, 10, 12, 14, 16),
        newly_added_orders=(16,),
        exclusion_equal_orders=(1, 2, 3, 4, 6),
        exclusion_mismatch_orders=(8, 10, 12, 14, 16),
    ),
)
