from __future__ import annotations

import re
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    while p != p.parent:
        if (p / "formal").exists() and (p / "README.md").exists():
            return p
        p = p.parent
    raise RuntimeError("Could not locate repo root (expected a 'formal' directory and README.md).")


REPO_ROOT = find_repo_root(Path(__file__))
ROADMAP_PATH = REPO_ROOT / "formal" / "docs" / "paper" / "PHYSICS_ROADMAP_v0.md"
RESULTS_PATH = REPO_ROOT / "formal" / "docs" / "paper" / "RESULTS_TABLE_v0.md"
COSMO_TARGET_PATH = (
    REPO_ROOT / "formal" / "docs" / "paper" / "DERIVATION_TARGET_COSMOLOGY_BACKGROUND_OBJECT_v0.md"
)
STATE_PATH = REPO_ROOT / "State_of_the_Theory.md"


def _read(path: Path) -> str:
    assert path.exists(), f"Missing required file: {path}"
    return path.read_text(encoding="utf-8")


def _extract_token_value(token: str, text: str) -> str:
    m = re.search(rf"{re.escape(token)}:\s*([A-Za-z0-9_\-,]+)", text)
    assert m is not None, f"Missing token: {token}"
    return m.group(1)


def _results_row_status(row_id: str, results_text: str) -> str:
    m = re.search(rf"^\|\s*{re.escape(row_id)}\s*\|\s*`([^`]+)`\s*\|", results_text, flags=re.MULTILINE)
    assert m is not None, f"Missing results row: {row_id}"
    return m.group(1)


def test_cosmo_closure_rows_are_declared_and_blocked() -> None:
    roadmap = _read(ROADMAP_PATH)
    results = _read(RESULTS_PATH)

    required_rows_raw = _extract_token_value("REQUIRED_COSMO_CLOSURE_ROWS", roadmap)
    required_rows = [row.strip() for row in required_rows_raw.split(",") if row.strip()]
    assert required_rows == ["TOE-COSMO-DER-01", "TOE-COSMO-DER-02"]

    adjudication = _extract_token_value("COSMO_BACKGROUND_ADJUDICATION", roadmap)
    for row_id in required_rows:
        status = _results_row_status(row_id, results)
        if adjudication == "NOT_YET_DISCHARGED":
            assert status.startswith("B-"), f"COSMO closure row must stay blocked pre-discharge: {row_id} -> {status}"
        else:
            assert not status.startswith("B-"), f"COSMO closure row must be non-blocked after discharge: {row_id} -> {status}"


def test_cosmo_roadmap_gates_remain_blocked_until_discharge() -> None:
    roadmap = _read(ROADMAP_PATH)
    adjudication = _extract_token_value("COSMO_BACKGROUND_ADJUDICATION", roadmap)

    if adjudication == "NOT_YET_DISCHARGED":
        assert _extract_token_value("PILLAR-COSMO_PHYSICS_STATUS", roadmap).startswith("OPEN_")
        assert _extract_token_value("PILLAR-COSMO_GOVERNANCE_STATUS", roadmap).startswith("OPEN_")
        assert _extract_token_value("PROCEED_GATE_COSMO", roadmap).startswith("BLOCKED_")
        assert _extract_token_value("MATRIX_CLOSURE_GATE_COSMO", roadmap).startswith("BLOCKED_")
    else:
        assert adjudication.startswith("DISCHARGED")
        assert _extract_token_value("PILLAR-COSMO_PHYSICS_STATUS", roadmap).startswith("CLOSED_")
        assert _extract_token_value("PILLAR-COSMO_GOVERNANCE_STATUS", roadmap).startswith("CLOSED_")
        assert _extract_token_value("PROCEED_GATE_COSMO", roadmap).startswith("ALLOWED_")
        assert _extract_token_value("MATRIX_CLOSURE_GATE_COSMO", roadmap).startswith("ALLOWED_")


def test_cosmo_target_and_state_pin_discharge_lane_tokens() -> None:
    target = _read(COSMO_TARGET_PATH)
    state = _read(STATE_PATH)

    assert (
        "COSMO_BACKGROUND_ADJUDICATION: NOT_YET_DISCHARGED" in state
        or "COSMO_BACKGROUND_ADJUDICATION: DISCHARGED_v0_BOUNDED" in state
    ), "State must expose either pre-discharge or discharged COSMO adjudication token."

    required_tokens = [
        "COSMO_BACKGROUND_FULL_DISCHARGE_EXIT_ROW_01_STATUS_v0: TOE-COSMO-DER-01_B-BLOCKED_PENDING_DISCHARGE",
        "COSMO_BACKGROUND_FULL_DISCHARGE_EXIT_ROW_02_STATUS_v0: TOE-COSMO-DER-02_B-BLOCKED_PENDING_DISCHARGE",
        "REQUIRED_COSMO_CLOSURE_ROWS: TOE-COSMO-DER-01,TOE-COSMO-DER-02",
        "PROCEED_GATE_COSMO: BLOCKED_v0_PHYSICS_NOT_CLOSED",
        "MATRIX_CLOSURE_GATE_COSMO: BLOCKED_v0_GOVERNANCE_NOT_CLOSED",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_01_NON_BLOCK_CONDITIONS_v0: CYCLE91_CANONICAL_ARTIFACT_AND_COMPLETION_CRITERIA_ARTIFACT_REQUIRED",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_02_NON_BLOCK_CONDITIONS_v0: ROADMAP_GATES_CLOSED_AND_EXPLICIT_AUTHORIZATION_PACKET_REQUIRED",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_AUTHORIZATION_PACKET_STATUS_v0: AUTHORIZATION_PENDING",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_AUTHORIZATION_PACKET_GATE_v0: LOCKED_UNTIL_EXPLICIT_AUTHORIZATION_PACKET_PRESENT_AND_ROADMAP_GATES_CLOSED",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_AUTHORIZATION_PACKET_ARTIFACT_v0: cosmo_full_discharge_exit_row_authorization_packet_cycle01_v0",
        "COSMO_FULL_DISCHARGE_PREDISCHARGE_TRANSITION_PROGRESS_CYCLE01_v0: PREDISCHARGE_TRANSITION_BUNDLE_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_PREDISCHARGE_TRANSITION_BUNDLE_GATE_v0: EXIT_ROW_CRITERIA_AND_AUTHORIZATION_PACKET_AND_REGISTRY_CHAIN_REQUIRED",
        "COSMO_FULL_DISCHARGE_ADJUDICATION_FLIP_BLOCK_v0: REQUIRE_EXPLICIT_DISCHARGE_GATE_CLOSURE",
        "COSMO_FULL_DISCHARGE_PREDISCHARGE_TRANSITION_BUNDLE_ARTIFACT_v0: cosmo_full_discharge_predischarge_transition_bundle_cycle01_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_TRANSITION_READINESS_PROGRESS_CYCLE02_v0: ACTIVE_DISCHARGE_IN_PROGRESS_READINESS_CHECKLIST_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_TRANSITION_READINESS_GATE_v0: PREDISCHARGE_BUNDLE_AND_EXPLICIT_ACTIVE_CHANGESET_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_TRANSITION_AUTHORIZATION_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_TRANSITION_READINESS_ARTIFACT_v0: cosmo_full_discharge_active_transition_readiness_checklist_cycle02_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_PROGRESS_CYCLE03_v0: ACTIVE_MODE_CHANGESET_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_GATE_v0: READINESS_CHECKLIST_AND_AUTHORIZATION_GATES_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_AUTHORITY_GATE_v0: LOCKED_UNTIL_EXPLICIT_ACTIVE_MODE_CHANGESET_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_packet_cycle03_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_VALIDATION_PROGRESS_CYCLE04_v0: ACTIVE_MODE_CHANGESET_VALIDATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_VALIDATION_GATE_v0: CYCLE03_CHANGESET_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_VALIDATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_VALIDATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_VALIDATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_validation_packet_cycle04_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RECONCILIATION_PROGRESS_CYCLE05_v0: ACTIVE_MODE_CHANGESET_RECONCILIATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RECONCILIATION_GATE_v0: CYCLE04_VALIDATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RECONCILIATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_RECONCILIATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RECONCILIATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_reconciliation_packet_cycle05_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ATTESTATION_PROGRESS_CYCLE06_v0: ACTIVE_MODE_CHANGESET_ATTESTATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ATTESTATION_GATE_v0: CYCLE05_RECONCILIATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ATTESTATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_ATTESTATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ATTESTATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_attestation_packet_cycle06_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RATIFICATION_PROGRESS_CYCLE07_v0: ACTIVE_MODE_CHANGESET_RATIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RATIFICATION_GATE_v0: CYCLE06_ATTESTATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RATIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_RATIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_RATIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_ratification_packet_cycle07_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CERTIFICATION_PROGRESS_CYCLE08_v0: ACTIVE_MODE_CHANGESET_CERTIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CERTIFICATION_GATE_v0: CYCLE07_RATIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CERTIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CERTIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CERTIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_certification_packet_cycle08_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONFIRMATION_PROGRESS_CYCLE09_v0: ACTIVE_MODE_CHANGESET_CONFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONFIRMATION_GATE_v0: CYCLE08_CERTIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CONFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_confirmation_packet_cycle09_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_PROGRESS_CYCLE10_v0: ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_GATE_v0: CYCLE09_CONFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ACKNOWLEDGMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_acknowledgment_packet_cycle10_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_AFFIRMATION_PROGRESS_CYCLE11_v0: ACTIVE_MODE_CHANGESET_AFFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_AFFIRMATION_GATE_v0: CYCLE10_ACKNOWLEDGMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_AFFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_AFFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_AFFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_affirmation_packet_cycle11_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ENDORSEMENT_PROGRESS_CYCLE12_v0: ACTIVE_MODE_CHANGESET_ENDORSEMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ENDORSEMENT_GATE_v0: CYCLE11_AFFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ENDORSEMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_ENDORSEMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_ENDORSEMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_endorsement_packet_cycle12_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONCURRENCE_PROGRESS_CYCLE13_v0: ACTIVE_MODE_CHANGESET_CONCURRENCE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONCURRENCE_GATE_v0: CYCLE12_ENDORSEMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONCURRENCE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CONCURRENCE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CONCURRENCE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_concurrence_packet_cycle13_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_PROGRESS_CYCLE14_v0: ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_GATE_v0: CYCLE13_CONCURRENCE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_COUNTERSIGNATURE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_countersignature_packet_cycle14_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ATTESTATION_PROGRESS_CYCLE15_v0: ACTIVE_MODE_CHANGESET_CO_ATTESTATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ATTESTATION_GATE_v0: CYCLE14_COUNTERSIGNATURE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ATTESTATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_ATTESTATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ATTESTATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_attestation_packet_cycle15_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RATIFICATION_PROGRESS_CYCLE16_v0: ACTIVE_MODE_CHANGESET_CO_RATIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RATIFICATION_GATE_v0: CYCLE15_CO_ATTESTATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RATIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RATIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RATIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_ratification_packet_cycle16_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_PROGRESS_CYCLE17_v0: ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_GATE_v0: CYCLE16_CO_RATIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CERTIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_certification_packet_cycle17_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_PROGRESS_CYCLE18_v0: ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_GATE_v0: CYCLE17_CO_CERTIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_confirmation_packet_cycle18_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_PROGRESS_CYCLE19_v0: ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_GATE_v0: CYCLE18_CO_CONFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ACKNOWLEDGMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_acknowledgment_packet_cycle19_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_PROGRESS_CYCLE20_v0: ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_GATE_v0: CYCLE19_CO_ACKNOWLEDGMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AFFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_affirmation_packet_cycle20_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_PROGRESS_CYCLE21_v0: ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_GATE_v0: CYCLE20_CO_AFFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_ENDORSEMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_endorsement_packet_cycle21_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_PROGRESS_CYCLE22_v0: ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_GATE_v0: CYCLE21_CO_ENDORSEMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_CONCURRENCE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_concurrence_packet_cycle22_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_PROGRESS_CYCLE23_v0: ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_GATE_v0: CYCLE22_CO_CONCURRENCE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_COUNTERSIGNATURE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_countersignature_packet_cycle23_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_PROGRESS_CYCLE24_v0: ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_GATE_v0: CYCLE23_CO_COUNTERSIGNATURE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_NOTARIZATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_notarization_packet_cycle24_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_PROGRESS_CYCLE25_v0: ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_GATE_v0: CYCLE24_CO_NOTARIZATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_LEGALIZATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_legalization_packet_cycle25_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_APOSTILLE_PROGRESS_CYCLE26_v0: ACTIVE_MODE_CHANGESET_CO_APOSTILLE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_APOSTILLE_GATE_v0: CYCLE25_CO_LEGALIZATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_APOSTILLE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_APOSTILLE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_APOSTILLE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_apostille_packet_cycle26_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_PROGRESS_CYCLE27_v0: ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_GATE_v0: CYCLE26_CO_APOSTILLE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_AUTHENTICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_authentication_packet_cycle27_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_VERIFICATION_PROGRESS_CYCLE28_v0: ACTIVE_MODE_CHANGESET_CO_VERIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_VERIFICATION_GATE_v0: CYCLE27_CO_AUTHENTICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_VERIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_VERIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_VERIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_verification_packet_cycle28_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_PROGRESS_CYCLE29_v0: ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_GATE_v0: CYCLE28_CO_VERIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECERTIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_recertification_packet_cycle29_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REVALIDATION_PROGRESS_CYCLE30_v0: ACTIVE_MODE_CHANGESET_CO_REVALIDATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REVALIDATION_GATE_v0: CYCLE29_CO_RECERTIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REVALIDATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REVALIDATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REVALIDATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_revalidation_packet_cycle30_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_PROGRESS_CYCLE31_v0: ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_GATE_v0: CYCLE30_CO_REVALIDATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAFFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reaffirmation_packet_cycle31_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REATTESTATION_PROGRESS_CYCLE32_v0: ACTIVE_MODE_CHANGESET_CO_REATTESTATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REATTESTATION_GATE_v0: CYCLE31_CO_REAFFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REATTESTATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REATTESTATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REATTESTATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reattestation_packet_cycle32_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_PROGRESS_CYCLE33_v0: ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_GATE_v0: CYCLE32_CO_REATTESTATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RERATIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reratification_packet_cycle33_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_PROGRESS_CYCLE34_v0: ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_GATE_v0: CYCLE33_CO_RERATIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REAUTHENTICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reauthentication_packet_cycle34_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_PROGRESS_CYCLE35_v0: ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_GATE_v0: CYCLE34_CO_REAUTHENTICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONFIRMATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reconfirmation_packet_cycle35_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_PROGRESS_CYCLE36_v0: ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_GATE_v0: CYCLE35_CO_RECONFIRMATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECONCURRENCE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reconcurrence_packet_cycle36_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_PROGRESS_CYCLE37_v0: ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_GATE_v0: CYCLE36_CO_RECONCURRENCE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECOUNTERSIGNATURE_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_recountersignature_packet_cycle37_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_PROGRESS_CYCLE38_v0: ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_GATE_v0: CYCLE37_CO_RECOUNTERSIGNATURE_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENDORSEMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reendorsement_packet_cycle38_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESEALING_PROGRESS_CYCLE39_v0: ACTIVE_MODE_CHANGESET_CO_RESEALING_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESEALING_GATE_v0: CYCLE38_CO_REENDORSEMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESEALING_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RESEALING_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESEALING_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_resealing_packet_cycle39_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESTAMPING_PROGRESS_CYCLE40_v0: ACTIVE_MODE_CHANGESET_CO_RESTAMPING_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESTAMPING_GATE_v0: CYCLE39_CO_RESEALING_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESTAMPING_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RESTAMPING_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RESTAMPING_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_restamping_packet_cycle40_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_PROGRESS_CYCLE41_v0: ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_GATE_v0: CYCLE40_CO_RESTAMPING_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REIMPRINTING_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reimprinting_packet_cycle41_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_PROGRESS_CYCLE42_v0: ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_GATE_v0: CYCLE41_CO_REIMPRINTING_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REINSCRIPTION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reinscription_packet_cycle42_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENACTMENT_PROGRESS_CYCLE43_v0: ACTIVE_MODE_CHANGESET_CO_REENACTMENT_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENACTMENT_GATE_v0: CYCLE42_CO_REINSCRIPTION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENACTMENT_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REENACTMENT_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REENACTMENT_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_reenactment_packet_cycle43_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_PROGRESS_CYCLE44_v0: ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_GATE_v0: CYCLE43_CO_REENACTMENT_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_RECODIFICATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_recodification_packet_cycle44_v0",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_PROGRESS_CYCLE45_v0: ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_PACKET_LOCK_PINNED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_GATE_v0: CYCLE44_CO_RECODIFICATION_PACKET_AND_AUTHORITY_GATE_REQUIRED",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_AUTHORITY_GATE_v0: LOCKED_UNTIL_ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_PACKET_AND_DISCHARGE_AUTHORITY_APPROVAL",
        "COSMO_FULL_DISCHARGE_ACTIVE_MODE_CHANGESET_CO_REPROMULGATION_ARTIFACT_v0: cosmo_full_discharge_active_mode_changeset_co_repromulgation_packet_cycle45_v0",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_READINESS_ARTIFACT_v0: cosmo_full_discharge_exit_row_readiness_cycle01_v0",
        "COSMO_FULL_DISCHARGE_EXIT_ROW_READINESS_GATE_v0: LOCKED_UNTIL_CHECKLIST_ARTIFACT_AND_ROW_STATUS_NON_BLOCKED",
        "formal/docs/paper/PILLAR_DISCHARGE_REGISTRY_v0.json",
        "formal/python/tests/test_pillar_full_discharge_completion_mechanics.py",
        "formal/toe_formal/ToeFormal/Cosmology/BackgroundObjectScaffold.lean",
        "formal/docs/paper/DERIVATION_TARGET_COSMOLOGY_BACKGROUND_FULL_DISCHARGE_EXIT_ROW_AUTHORIZATION_PACKET_v0.md",
        "formal/output/cosmo_full_discharge_exit_row_authorization_packet_cycle01_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_exit_row_authorization_packet_gate.py",
        "formal/output/cosmo_full_discharge_exit_row_readiness_cycle01_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_exit_row_readiness_gate.py",
        "formal/output/cosmo_full_discharge_predischarge_transition_bundle_cycle01_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_predischarge_transition_bundle_gate.py",
        "formal/output/cosmo_full_discharge_active_transition_readiness_checklist_cycle02_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_transition_readiness_cycle02_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_packet_cycle03_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_cycle03_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_validation_packet_cycle04_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_validation_cycle04_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_reconciliation_packet_cycle05_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_reconciliation_cycle05_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_attestation_packet_cycle06_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_attestation_cycle06_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_ratification_packet_cycle07_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_ratification_cycle07_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_certification_packet_cycle08_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_certification_cycle08_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_confirmation_packet_cycle09_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_confirmation_cycle09_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_acknowledgment_packet_cycle10_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_acknowledgment_cycle10_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_affirmation_packet_cycle11_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_affirmation_cycle11_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_endorsement_packet_cycle12_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_endorsement_cycle12_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_concurrence_packet_cycle13_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_concurrence_cycle13_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_countersignature_packet_cycle14_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_countersignature_cycle14_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_attestation_packet_cycle15_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_attestation_cycle15_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_ratification_packet_cycle16_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_ratification_cycle16_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_certification_packet_cycle17_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_certification_cycle17_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_confirmation_packet_cycle18_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_confirmation_cycle18_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_acknowledgment_packet_cycle19_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_acknowledgment_cycle19_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_affirmation_packet_cycle20_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_affirmation_cycle20_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_endorsement_packet_cycle21_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_endorsement_cycle21_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_concurrence_packet_cycle22_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_concurrence_cycle22_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_countersignature_packet_cycle23_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_countersignature_cycle23_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_notarization_packet_cycle24_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_notarization_cycle24_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_legalization_packet_cycle25_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_legalization_cycle25_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_apostille_packet_cycle26_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_apostille_cycle26_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_authentication_packet_cycle27_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_authentication_cycle27_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_verification_packet_cycle28_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_verification_cycle28_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_recertification_packet_cycle29_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_recertification_cycle29_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_revalidation_packet_cycle30_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_revalidation_cycle30_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reaffirmation_packet_cycle31_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reaffirmation_cycle31_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reattestation_packet_cycle32_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reattestation_cycle32_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reratification_packet_cycle33_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reratification_cycle33_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reauthentication_packet_cycle34_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reauthentication_cycle34_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reconfirmation_packet_cycle35_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reconfirmation_cycle35_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reconcurrence_packet_cycle36_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reconcurrence_cycle36_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_recountersignature_packet_cycle37_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_recountersignature_cycle37_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reendorsement_packet_cycle38_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reendorsement_cycle38_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_resealing_packet_cycle39_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_resealing_cycle39_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_restamping_packet_cycle40_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_restamping_cycle40_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reimprinting_packet_cycle41_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reimprinting_cycle41_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reinscription_packet_cycle42_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reinscription_cycle42_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_reenactment_packet_cycle43_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_reenactment_cycle43_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_recodification_packet_cycle44_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_recodification_cycle44_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_repromulgation_packet_cycle45_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_repromulgation_cycle45_gate.py",
        "formal/output/cosmo_full_discharge_active_mode_changeset_co_repromulgation_confirmation_packet_cycle46_v0.json",
        "formal/python/tests/test_cosmo_full_derivation_active_mode_changeset_co_repromulgation_confirmation_cycle46_gate.py",
        "formal/python/tests/test_cosmo_full_derivation_discharge_lane_gate.py",
    ]

    for token in required_tokens:
        assert token in target, f"COSMO target missing discharge-lane token: {token}"
        assert token in state, f"State missing COSMO discharge-lane token: {token}"
