from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from formal.python.meta.repo_environment import find_repo_root


REPO_ROOT = find_repo_root(Path(__file__))
LEAN_ROOT = REPO_ROOT / "formal" / "toe_formal"
MODULE_TREE = LEAN_ROOT / "ToeFormal"
OUTPUT_PATH = LEAN_ROOT / "ToeFormalAll.lean"


def tracked_module_names() -> list[str]:
    completed = subprocess.run(
        [
            "git",
            "ls-files",
            "-z",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            "formal/toe_formal/ToeFormal",
        ],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
    )
    candidates = sorted(
        item.decode("utf-8", errors="strict")
        for item in completed.stdout.split(b"\0")
        if item
    )
    modules: list[str] = []
    for relative_text in candidates:
        path = REPO_ROOT / relative_text
        if path.suffix != ".lean" or not path.exists():
            # A pending tracked deletion is intentionally absent from the next root.
            continue
        relative = path.relative_to(LEAN_ROOT).with_suffix("")
        modules.append(".".join(relative.parts))
    return modules


def render_aggregate() -> bytes:
    modules = tracked_module_names()
    lines = [
        "/-",
        "Generated by formal.python.tools.generate_lean_all_modules_aggregate.",
        "This validation root imports every tracked ToeFormal module; it does not",
        "promote any theorem, discharge any axiom, or change scientific authority.",
        "-/",
        "",
    ]
    lines.extend(f"import {module}" for module in modules)
    lines.extend(
        [
            "",
            "namespace ToeFormalAll",
            "",
            f'def trackedModuleCount : Nat := {len(modules)}',
            "",
            "end ToeFormalAll",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the all-module Lean validation root.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail when the aggregate is stale (default).")
    mode.add_argument("--write", action="store_true", help="Write the deterministic aggregate.")
    args = parser.parse_args()

    expected = render_aggregate()
    current = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else None
    if args.write:
        if current != expected:
            OUTPUT_PATH.write_bytes(expected)
            print(f"generate_lean_all_modules_aggregate: wrote {len(tracked_module_names())} modules")
        else:
            print("generate_lean_all_modules_aggregate: already current")
        return 0

    if current != expected:
        print("generate_lean_all_modules_aggregate: FAILED aggregate drift")
        return 1
    print(f"generate_lean_all_modules_aggregate: OK modules={len(tracked_module_names())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
