from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from formal.python.meta.repo_environment import find_repo_root


REPO_ROOT = find_repo_root(Path(__file__))
LEAN_ROOT = REPO_ROOT / "formal" / "toe_formal"
MODULE_TREE = LEAN_ROOT / "ToeFormal"
OUTPUT_PATH = LEAN_ROOT / "ToeFormalAll.lean"


def _module_names(*, include_untracked: bool) -> list[str]:
    selection = ["--cached"]
    if include_untracked:
        selection.extend(["--others", "--exclude-standard"])
    completed = subprocess.run(
        [
            "git",
            "ls-files",
            "-z",
            *selection,
            "--",
            "formal/toe_formal/ToeFormal",
        ],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
    )
    candidates = sorted(
        item.decode("utf-8", errors="strict")
        for item in completed.stdout.split(b"\0")
        if item
    )
    modules: list[str] = []
    for relative_text in candidates:
        path = REPO_ROOT / relative_text
        if path.suffix != ".lean" or not path.exists():
            # A pending tracked deletion is intentionally absent from the next root.
            continue
        relative = path.relative_to(LEAN_ROOT).with_suffix("")
        modules.append(".".join(relative.parts))
    return modules


def committed_module_names() -> list[str]:
    return _module_names(include_untracked=False)


def working_tree_module_names() -> list[str]:
    return _module_names(include_untracked=True)


def tracked_module_names() -> list[str]:
    """Backward-compatible name for the committed-source inventory."""

    return committed_module_names()


def render_aggregate(*, scope: str = "committed") -> bytes:
    if scope == "committed":
        modules = committed_module_names()
        scope_description = "every committed ToeFormal module"
        count_name = "committedModuleCount"
    elif scope == "working-tree":
        modules = working_tree_module_names()
        scope_description = "every committed and untracked working-tree ToeFormal module"
        count_name = "workingTreeModuleCount"
    else:
        raise ValueError(f"unsupported aggregate scope: {scope}")
    lines = [
        "/-",
        "Generated by formal.python.tools.generate_lean_all_modules_aggregate.",
        f"This validation root imports {scope_description}; it does not",
        "promote any theorem, discharge any axiom, or change scientific authority.",
        "-/",
        "",
    ]
    lines.extend(f"import {module}" for module in modules)
    lines.extend(
        [
            "",
            "namespace ToeFormalAll",
            "",
            f'def {count_name} : Nat := {len(modules)}',
            "",
            "end ToeFormalAll",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the all-module Lean validation root.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail when the aggregate is stale (default).")
    mode.add_argument("--write", action="store_true", help="Write the deterministic aggregate.")
    parser.add_argument(
        "--scope",
        choices=("committed", "working-tree"),
        default="committed",
        help="Select committed-source validation or an explicitly local working-tree inventory.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Required output for working-tree scope; committed scope defaults to ToeFormalAll.lean.",
    )
    args = parser.parse_args()

    if args.scope == "working-tree" and args.output is None:
        parser.error("--scope working-tree requires --output outside canonical source")
    output = args.output.resolve() if args.output is not None else OUTPUT_PATH
    expected = render_aggregate(scope=args.scope)
    current = output.read_bytes() if output.exists() else None
    if args.write:
        if current != expected:
            output.write_bytes(expected)
            count = (
                len(committed_module_names())
                if args.scope == "committed"
                else len(working_tree_module_names())
            )
            print(f"generate_lean_all_modules_aggregate: wrote {count} modules scope={args.scope}")
        else:
            print("generate_lean_all_modules_aggregate: already current")
        return 0

    if current != expected:
        print("generate_lean_all_modules_aggregate: FAILED aggregate drift")
        return 1
    count = (
        len(committed_module_names())
        if args.scope == "committed"
        else len(working_tree_module_names())
    )
    print(f"generate_lean_all_modules_aggregate: OK modules={count} scope={args.scope}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
